# Form implementation generated from reading ui file 'Help.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form9(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 325)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(400, 325))
        Form.setMaximumSize(QtCore.QSize(400, 325))
        Form.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        Form.setStyleSheet("background-color:\"lightgreen\"\n"
"")
        self.board_label0_3 = QtWidgets.QLabel(Form)
        self.board_label0_3.setGeometry(QtCore.QRect(20, 10, 151, 28))
        self.board_label0_3.setStyleSheet("background-color:\"lightblue\"\n"
"")
        self.board_label0_3.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.board_label0_3.setObjectName("board_label0_3")
        self.board_label1_5 = QtWidgets.QLabel(Form)
        self.board_label1_5.setGeometry(QtCore.QRect(220, 10, 151, 28))
        self.board_label1_5.setStyleSheet("background-color:\"blue\"\n"
"")
        self.board_label1_5.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.board_label1_5.setObjectName("board_label1_5")
        self.board_label2_2 = QtWidgets.QLabel(Form)
        self.board_label2_2.setGeometry(QtCore.QRect(20, 50, 151, 28))
        self.board_label2_2.setStyleSheet("background-color:\"#ffdead\"\n"
"")
        self.board_label2_2.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.board_label2_2.setObjectName("board_label2_2")
        self.board_label0_7 = QtWidgets.QLabel(Form)
        self.board_label0_7.setGeometry(QtCore.QRect(220, 50, 151, 28))
        self.board_label0_7.setStyleSheet("background-color:\"red\"\n"
"")
        self.board_label0_7.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.board_label0_7.setObjectName("board_label0_7")
        self.board_label7_7 = QtWidgets.QLabel(Form)
        self.board_label7_7.setGeometry(QtCore.QRect(60, 100, 271, 27))
        self.board_label7_7.setStyleSheet("background-color:\"lightpink\"\n"
"")
        self.board_label7_7.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.board_label7_7.setObjectName("board_label7_7")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 140, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(100, 170, 47, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(160, 170, 47, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(210, 180, 47, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(260, 190, 47, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Scrabble"))
        self.board_label0_3.setText(_translate("Form", "DL - Double Letter"))
        self.board_label1_5.setText(_translate("Form", "TL- Tripple Letter"))
        self.board_label2_2.setText(_translate("Form", "DW - Double Word"))
        self.board_label0_7.setText(_translate("Form", "TW - Triple Word"))
        self.board_label7_7.setText(_translate("Form", "* - Starting tile (must be used in the first move)"))
        self.label.setText(_translate("Form", "Points for each letter"))
        self.label_2.setText(_translate("Form", "A - 1\n"
"B - 3\n"
"C - 3\n"
"D - 2\n"
"E - 1\n"
"F - 4\n"
"G - 2"))
        self.label_3.setText(_translate("Form", "H - 4\n"
"I - 1\n"
"J - 8\n"
"K - 5\n"
"L - 1\n"
"M - 3"))
        self.label_4.setText(_translate("Form", "N - 1\n"
"O - 1\n"
"P - 3\n"
"Q - 10\n"
"R - 1\n"
"S - 1\n"
"T - 1"))
        self.label_5.setText(_translate("Form", "U - 1\n"
"V - 4\n"
"W - 4\n"
"X - 8\n"
"Y - 4\n"
"Z - 10"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form9()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
