# Form implementation generated from reading ui file 'WritePlayerNames2.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from player import Player
from gui_classes.board_gui_controller import *
import menu
import choose_number


class Ui_Form3(object):

    def __init__(self, aux_number_of_players):
        self.number_of_players = aux_number_of_players

    def back_to_menu(self):
        self.window2 = QtWidgets.QMainWindow()
        self.ui = menu.Ui_Form()
        self.ui.setupUi(self.window2)
        self.window2.show()

    def setupUi(self, Form):
        self.check_length_names = False
        self.form = Form
        Form.setObjectName("Form")
        Form.resize(700, 791)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(700, 791))
        Form.setMaximumSize(QtCore.QSize(700, 791))
        Form.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        Form.setStyleSheet("background-color:\"green\"\n"
"")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 700, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(700, 281))
        self.label.setMaximumSize(QtCore.QSize(700, 281))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/Logo_2.png"))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 660, 701, 131))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.playButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setMinimumSize(QtCore.QSize(230, 35))
        self.playButton.setMaximumSize(QtCore.QSize(230, 35))
        self.playButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.playButton.setStyleSheet("background-color:\"lightblue\"\n"
"")
        self.playButton.setAutoDefault(False)
        self.playButton.setObjectName("playButton")
        self.playButton.clicked.connect(self.clicked_play)
        self.playButton.clicked.connect(self.check_length)
        self.playButton.clicked.connect(self.error)
        self.playButton.clicked.connect(self.open_choice)

        self.verticalLayout_4.addWidget(self.playButton)

        self.go_backButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.exitButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.go_backButton.setSizePolicy(sizePolicy)
        self.go_backButton.setMinimumSize(QtCore.QSize(230, 35))
        self.go_backButton.setMaximumSize(QtCore.QSize(230, 35))
        self.go_backButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.go_backButton.setStyleSheet("background-color:\"lightblue\"\n"
"")
        self.go_backButton.setObjectName("go_backButton")
        self.go_backButton.clicked.connect(self.back_to_menu)
        self.go_backButton.clicked.connect(Form.close)

        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setMinimumSize(QtCore.QSize(230, 35))
        self.exitButton.setMaximumSize(QtCore.QSize(230, 35))
        self.exitButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.exitButton.setStyleSheet("background-color:\"lightblue\"\n"
"")
        self.exitButton.setObjectName("exitButton")
        self.exitButton.clicked.connect(Form.close)

        self.verticalLayout_4.addWidget(self.go_backButton)
        self.verticalLayout_4.addWidget(self.exitButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.p1Label = QtWidgets.QLabel(Form)
        self.p1Label.setGeometry(QtCore.QRect(260, 330, 63, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p1Label.sizePolicy().hasHeightForWidth())
        self.p1Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p1Label.setFont(font)
        self.p1Label.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.p1Label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.p1Label.setAlignment(QtCore.Qt.Alignment.AlignRight|QtCore.Qt.Alignment.AlignTrailing|QtCore.Qt.Alignment.AlignVCenter)
        self.p1Label.setObjectName("p1Label")
        self.p2Label = QtWidgets.QLabel(Form)
        self.p2Label.setGeometry(QtCore.QRect(260, 410, 63, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p2Label.sizePolicy().hasHeightForWidth())
        self.p2Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p2Label.setFont(font)
        self.p2Label.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.p2Label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.p2Label.setAlignment(QtCore.Qt.Alignment.AlignRight|QtCore.Qt.Alignment.AlignTrailing|QtCore.Qt.Alignment.AlignVCenter)
        self.p2Label.setObjectName("p2Label")
        self.p3Label = QtWidgets.QLabel(Form)
        self.p3Label.setGeometry(QtCore.QRect(260, 500, 63, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p3Label.sizePolicy().hasHeightForWidth())
        self.p3Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p3Label.setFont(font)
        self.p3Label.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.p3Label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.p3Label.setAlignment(QtCore.Qt.Alignment.AlignRight|QtCore.Qt.Alignment.AlignTrailing|QtCore.Qt.Alignment.AlignVCenter)
        self.p3Label.setObjectName("p3Label")
        self.p4Label = QtWidgets.QLabel(Form)
        self.p4Label.setGeometry(QtCore.QRect(260, 580, 63, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.p4Label.sizePolicy().hasHeightForWidth())
        self.p4Label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.p4Label.setFont(font)
        self.p4Label.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.p4Label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.p4Label.setAlignment(QtCore.Qt.Alignment.AlignRight|QtCore.Qt.Alignment.AlignTrailing|QtCore.Qt.Alignment.AlignVCenter)
        self.p4Label.setObjectName("p4Label")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(330, 330, 200, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMinimumSize(QtCore.QSize(200, 30))
        self.textEdit.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit.setFont(font)
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setEnabled(True)
        self.textEdit_2.setGeometry(QtCore.QRect(330, 410, 200, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMinimumSize(QtCore.QSize(200, 30))
        self.textEdit_2.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setEnabled(True)
        self.textEdit_3.setGeometry(QtCore.QRect(330, 500, 200, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_3.sizePolicy().hasHeightForWidth())
        self.textEdit_3.setSizePolicy(sizePolicy)
        self.textEdit_3.setMinimumSize(QtCore.QSize(200, 30))
        self.textEdit_3.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(Form)
        self.textEdit_4.setEnabled(True)
        self.textEdit_4.setGeometry(QtCore.QRect(330, 580, 200, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_4.sizePolicy().hasHeightForWidth())
        self.textEdit_4.setSizePolicy(sizePolicy)
        self.textEdit_4.setMinimumSize(QtCore.QSize(200, 30))
        self.textEdit_4.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(220, 300, 250, 13))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.chooseNumberhelp = choose_number.Ui_Form2

        self.players = []

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


        if self.number_of_players == 2:
            self.font = QtGui.QFont()
            self.font.setPointSize(12)
            self.font.setStrikeOut(True)
            self.p3Label.setFont(self.font)
            self.p3Label.setStyleSheet("color: red")

            self.p4Label.setFont(self.font)
            self.p4Label.setStyleSheet("color: red")

            self.textEdit_3.setEnabled(False)
            self.textEdit_4.setEnabled(False)


        if self.number_of_players == 3:
            self.font = QtGui.QFont()
            self.font.setPointSize(12)
            self.font.setStrikeOut(True)
            self.p4Label.setFont(self.font)
            self.p4Label.setStyleSheet("color: red")

            self.textEdit_4.setEnabled(False)

    def open_choice(self):
        if self.check_length_names is True:
            # self.window2 = QtWidgets.QMainWindow()
            # self.ui = board_gui_handler.Ui_board_window(self.number_of_players, self.players)
            # self.ui.setupUi(self.window2)
            # self.window2.show()
            self.board = Board_gui(self.number_of_players, self.players)
            self.board.show()
            self.form.close()

    def clicked_play(self):
        self.player1 = Player(self.textEdit.toPlainText(), [])
        self.player2 = Player(self.textEdit_2.toPlainText(), [])

        if self.number_of_players != 2:
            self.player3 = Player(self.textEdit_3.toPlainText(), [])

        if self.number_of_players == 4:
            self.player4 = Player(self.textEdit_4.toPlainText(), [])

        for i in range(self.number_of_players):
            self.players.append(eval("self.player" + str(i+1)))

    def check_length(self):
        text1 = self.textEdit.toPlainText()
        text2 = self.textEdit_2.toPlainText()
        if self.number_of_players == 2:
            if len(text1) >= 3 and len(text1) <= 20 and len(text2) >= 3 and len(text2) <= 20:
                self.check_length_names = True

        else:
            text3 = self.textEdit_3.toPlainText()
            if self.number_of_players == 3:
                if len(text1) >= 3 and len(text1) <= 20 and len(text2) >= 3 and len(text2) <= 20 and len(text3) >= 3 and len(text3) <= 20:
                    self.check_length_names = True

            else:
                text4 = self.textEdit_4.toPlainText()
                if len(text1) >= 3 and len(text1) <= 20 and len(text2) >= 3 and len(text2) <= 20 and len(text3) >= 3 and len(text3) <= 20 and len(text4) >= 3 and len(text4) <= 20:
                    self.check_length_names = True

    def error(self):
        if self.check_length_names is False:
            self.label_2.setText("The username must consist of 3-20 characters")
            self.label_2.setStyleSheet("color: red")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Scrabble"))
        self.playButton.setText(_translate("Form", "Play"))
        self.exitButton.setText(_translate("Form", "Exit"))
        self.go_backButton.setText(_translate("Form", "Back to menu"))
        self.p1Label.setText(_translate("Form", "Player 1:"))
        self.p2Label.setText(_translate("Form", "Player 2:"))
        self.p3Label.setText(_translate("Form", "Player 3:"))
        self.p4Label.setText(_translate("Form", "Player 4:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form3(3)
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
