# Form implementation generated from reading ui file 'Rules.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import menu


class Ui_Form10(object):

    def back_to_menu(self):
        self.window3 = QtWidgets.QMainWindow()
        self.ui = menu.Ui_Form()
        self.ui.setupUi(self.window3)
        self.window3.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 769)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icon1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(700, 769))
        Form.setMaximumSize(QtCore.QSize(700, 769))
        Form.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        Form.setStyleSheet("background-color:\"green\"\n"
"")
        self.ladelabel = QtWidgets.QLabel(Form)
        self.ladelabel.setGeometry(QtCore.QRect(320, 40, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ladelabel.setFont(font)
        self.ladelabel.setObjectName("ladelabel")
        self.backButton = QtWidgets.QPushButton(Form)
        self.backButton.setGeometry(QtCore.QRect(230, 700, 230, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backButton.sizePolicy().hasHeightForWidth())
        self.backButton.setSizePolicy(sizePolicy)
        self.backButton.setMinimumSize(QtCore.QSize(230, 35))
        self.backButton.setMaximumSize(QtCore.QSize(230, 35))
        self.backButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.backButton.setStyleSheet("background-color:\"lightblue\"\n"
"")
        self.backButton.setAutoDefault(False)
        self.backButton.setObjectName("backButton")
        self.backButton.clicked.connect(self.back_to_menu)
        self.backButton.clicked.connect(Form.close)

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 120, 501, 541))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:\"green\"\n"
"")
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Scrabble"))
        self.ladelabel.setText(_translate("Form", "Rules"))
        self.backButton.setText(_translate("Form", "Back to menu"))
        self.label.setText(_translate("Form", "1 point: A, E, I, O, U, L, N, S, T, R\n"
"2 points: D, G\n"
"3 points: B, C, M, P\n"
"4 points: F, H, V, W, Y\n"
"5 points: K\n"
"8 points: J, X\n"
"10 points: Q, Z\n"
"\n"
"DW (Double Word) - Points for created word are multiplied by 2\n"
"TW (Triple Word) - Points for created word are multiplied by 3\n"
"DL (Double Letter) - Points for put letter are multiplied by 2\n"
"TL (Triple Letter) - Points for put letter are multiplied by 3\n"
"\n"
"PLAYER-END-OF-PARTICIPATING-IN-GAME:\n"
"    The player is no longer allowed to participate in the game if they:\n"
"        1) Swapped letters 3 times in a row\n"
"        2) Created a non-existent word or didn't put a single letter on\n"
"            a board 2 times in a row\n"
"\n"
"\n"
"END-OF-GAME: \n"
"    The game will be finished when less than 7 letters are left in bag\n"
"                                  OR\n"
"    All of the players are not permitted to play due to number of swapped\n"
"    letters few times in a row or not creating existing word or not putting a letter\n"
"    on a board few times in a row\n"
"\n"
"IMPORTANT!\n"
"    The player is not allowed to create a new word from the tiles\n"
"    which have been put by him during the same move"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form10()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
