# Form implementation generated from reading ui file '/Users/mzieba/Documents/szkola/code/Scrabble_with_GUI/templates/entry_window.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_entryWindow(object):
    def setupUi(self, entryWindow):
        entryWindow.setObjectName("entryWindow")
        entryWindow.resize(412, 507)
        self.centralwidget = QtWidgets.QWidget(entryWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dropFrame = QtWidgets.QFrame(self.centralwidget)
        self.dropFrame.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.dropFrame.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(39, 105, 47);\n"
"    color: rgb(133, 255, 120);\n"
"    border-radius: 10px;\n"
"}")
        self.dropFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dropFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dropFrame.setObjectName("dropFrame")
        self.name = QtWidgets.QLabel(self.dropFrame)
        self.name.setGeometry(QtCore.QRect(-130, 140, 661, 61))
        font = QtGui.QFont()
        font.setPointSize(50)
        self.name.setFont(font)
        self.name.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.name.setObjectName("name")
        self.triggerButton = QtWidgets.QPushButton(self.dropFrame)
        self.triggerButton.setGeometry(QtCore.QRect(160, 240, 81, 31))
        self.triggerButton.setStyleSheet("QPushButton{\n"
"        color:black;\n"
"        background-color: rgb(150, 38, 26);\n"
"        border-radius:7px;\n"
"}QPushButton::pressed{\n"
"  box-shadow: 0px 15px 20px rgba(46, 229, 157, 0.4);\n"
"    background-color: rgb(174, 69, 77);\n"
"}")
        self.triggerButton.setObjectName("triggerButton")
        self.exitButton = QtWidgets.QPushButton(self.dropFrame)
        self.exitButton.setGeometry(QtCore.QRect(370, 10, 14, 14))
        self.exitButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 40, 54);\n"
"    border-radius: 7px;\n"
"    border: none\n"
"}")
        self.exitButton.setText("")
        self.exitButton.setCheckable(False)
        self.exitButton.setDefault(False)
        self.exitButton.setFlat(False)
        self.exitButton.setObjectName("exitButton")
        self.emoji_label = QtWidgets.QLabel(self.dropFrame)
        self.emoji_label.setGeometry(QtCore.QRect(120, 300, 151, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.emoji_label.setFont(font)
        self.emoji_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.emoji_label.setObjectName("emoji_label")
        self.name.raise_()
        self.triggerButton.raise_()
        self.emoji_label.raise_()
        self.exitButton.raise_()
        self.horizontalLayout.addWidget(self.dropFrame)
        entryWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(entryWindow)
        QtCore.QMetaObject.connectSlotsByName(entryWindow)

    def retranslateUi(self, entryWindow):
        _translate = QtCore.QCoreApplication.translate
        entryWindow.setWindowTitle(_translate("entryWindow", "MainWindow"))
        self.name.setText(_translate("entryWindow", "<html><head/><body><p><span style=\" font-weight:700;\">Scrabble v01</span></p><p><br/></p></body></html>"))
        self.triggerButton.setText(_translate("entryWindow", "zagraj"))
        self.emoji_label.setText(_translate("entryWindow", "<html><head/><body><p><img src=\":/newPrefix/images/3x.png\"/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    entryWindow = QtWidgets.QMainWindow()
    ui = Ui_entryWindow()
    ui.setupUi(entryWindow)
    entryWindow.show()
    sys.exit(app.exec())
