# Form implementation generated from reading ui file '/Users/mzieba/Documents/szkola/code/Scrabble_with_GUI/templates/hotseat_players_login_window.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_hotseat_players_login_window(object):
    def setupUi(self, hotseat_players_login_window):
        hotseat_players_login_window.setObjectName("hotseat_players_login_window")
        hotseat_players_login_window.resize(649, 698)
        self.centralwidget = QtWidgets.QWidget(hotseat_players_login_window)
        self.centralwidget.setObjectName("centralwidget")
        self.menu_frame = QtWidgets.QFrame(self.centralwidget)
        self.menu_frame.setGeometry(QtCore.QRect(10, 20, 581, 621))
        self.menu_frame.setStyleSheet("QFrame {\n"
"    border-radius: 7px;\n"
"    color: rgb(62, 231, 41);\n"
"    background-color: rgb(40, 109, 50);\n"
"}\n"
"")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.name_label = QtWidgets.QLabel(self.menu_frame)
        self.name_label.setGeometry(QtCore.QRect(-40, 20, 361, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.exit_button = QtWidgets.QPushButton(self.menu_frame)
        self.exit_button.setGeometry(QtCore.QRect(560, 7, 14, 14))
        self.exit_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 40, 54);\n"
"    border-radius: 7px;\n"
"    border: none\n"
"}")
        self.exit_button.setText("")
        self.exit_button.setCheckable(False)
        self.exit_button.setDefault(False)
        self.exit_button.setFlat(False)
        self.exit_button.setObjectName("exit_button")
        self.game_mode_frame = QtWidgets.QFrame(self.menu_frame)
        self.game_mode_frame.setGeometry(QtCore.QRect(45, 90, 211, 111))
        self.game_mode_frame.setStyleSheet("QFrame {\n"
"background-color: rgb(22, 60, 27);\n"
"}\n"
"")
        self.game_mode_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.game_mode_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.game_mode_frame.setObjectName("game_mode_frame")
        self.game_mode_label = QtWidgets.QLabel(self.game_mode_frame)
        self.game_mode_label.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.game_mode_label.setFont(font)
        self.game_mode_label.setStyleSheet("QLabel {\n"
"    color: rgb(226, 224, 158);\n"
"\n"
"}")
        self.game_mode_label.setObjectName("game_mode_label")
        self.hotseat_mode_label = QtWidgets.QLabel(self.game_mode_frame)
        self.hotseat_mode_label.setGeometry(QtCore.QRect(100, 55, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hotseat_mode_label.setFont(font)
        self.hotseat_mode_label.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(62, 232, 41);\n"
"}")
        self.hotseat_mode_label.setObjectName("hotseat_mode_label")
        self.hotseat_icon_label = QtWidgets.QLabel(self.game_mode_frame)
        self.hotseat_icon_label.setGeometry(QtCore.QRect(30, 50, 61, 41))
        self.hotseat_icon_label.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.hotseat_icon_label.setText("")
        self.hotseat_icon_label.setObjectName("hotseat_icon_label")
        self.return_to_menu_button = QtWidgets.QPushButton(self.menu_frame)
        self.return_to_menu_button.setGeometry(QtCore.QRect(260, 580, 71, 32))
        self.return_to_menu_button.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"image: url(:/newPrefix/images/returnleft.png);\n"
"}\n"
"")
        self.return_to_menu_button.setText("")
        self.return_to_menu_button.setObjectName("return_to_menu_button")
        self.login_stacked_widget = QtWidgets.QStackedWidget(self.menu_frame)
        self.login_stacked_widget.setGeometry(QtCore.QRect(35, 250, 511, 331))
        self.login_stacked_widget.setStyleSheet("QWidget{\n"
"    background-color: transparent;\n"
"}")
        self.login_stacked_widget.setObjectName("login_stacked_widget")
        self.players2_page = QtWidgets.QWidget()
        self.players2_page.setStyleSheet("QFrame {\n"
"background-color: transparent;\n"
"}")
        self.players2_page.setObjectName("players2_page")
        self.players2_frame = QtWidgets.QFrame(self.players2_page)
        self.players2_frame.setGeometry(QtCore.QRect(10, 0, 501, 331))
        self.players2_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.players2_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.players2_frame.setObjectName("players2_frame")
        self.player1of2_login_frame = QtWidgets.QFrame(self.players2_frame)
        self.player1of2_login_frame.setGeometry(QtCore.QRect(40, 40, 201, 161))
        self.player1of2_login_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 78, 131);\n"
"border-radius: 15;\n"
"}\n"
"\n"
"")
        self.player1of2_login_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.player1of2_login_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.player1of2_login_frame.setObjectName("player1of2_login_frame")
        self.player1of2_stacked = QtWidgets.QStackedWidget(self.player1of2_login_frame)
        self.player1of2_stacked.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.player1of2_stacked.setObjectName("player1of2_stacked")
        self.player1of2_logged_stacked = QtWidgets.QWidget()
        self.player1of2_logged_stacked.setObjectName("player1of2_logged_stacked")
        self.player_icon_label_10 = QtWidgets.QLabel(self.player1of2_logged_stacked)
        self.player_icon_label_10.setGeometry(QtCore.QRect(20, 30, 41, 31))
        self.player_icon_label_10.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_10.setText("")
        self.player_icon_label_10.setObjectName("player_icon_label_10")
        self.correct_cred_label_4 = QtWidgets.QLabel(self.player1of2_logged_stacked)
        self.correct_cred_label_4.setGeometry(QtCore.QRect(20, 70, 151, 20))
        self.correct_cred_label_4.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(62, 232, 41);\n"
"}")
        self.correct_cred_label_4.setObjectName("correct_cred_label_4")
        self.player1of2_name_label = QtWidgets.QLabel(self.player1of2_logged_stacked)
        self.player1of2_name_label.setGeometry(QtCore.QRect(80, 35, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.player1of2_name_label.setFont(font)
        self.player1of2_name_label.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.player1of2_name_label.setObjectName("player1of2_name_label")
        self.player1of2_stacked.addWidget(self.player1of2_logged_stacked)
        self.player1of2_login_stacked = QtWidgets.QWidget()
        self.player1of2_login_stacked.setObjectName("player1of2_login_stacked")
        self.label_6 = QtWidgets.QLabel(self.player1of2_login_stacked)
        self.label_6.setGeometry(QtCore.QRect(55, 10, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.label_6.setObjectName("label_6")
        self.player_icon_label_4 = QtWidgets.QLabel(self.player1of2_login_stacked)
        self.player_icon_label_4.setGeometry(QtCore.QRect(10, 5, 41, 31))
        self.player_icon_label_4.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_4.setText("")
        self.player_icon_label_4.setObjectName("player_icon_label_4")
        self.p1of2_login = QtWidgets.QLineEdit(self.player1of2_login_stacked)
        self.p1of2_login.setGeometry(QtCore.QRect(50, 50, 113, 21))
        self.p1of2_login.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(52, 40, 70);\n"
"}")
        self.p1of2_login.setObjectName("p1of2_login")
        self.p1of2_pass = QtWidgets.QLineEdit(self.player1of2_login_stacked)
        self.p1of2_pass.setGeometry(QtCore.QRect(50, 80, 113, 21))
        self.p1of2_pass.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(52, 40, 70);\n"
"lineedit-password-character: 9679;\n"
"}")
        self.p1of2_pass.setObjectName("p1of2_pass")
        self.wrong_cred_label_1of2 = QtWidgets.QLabel(self.player1of2_login_stacked)
        self.wrong_cred_label_1of2.setGeometry(QtCore.QRect(20, 110, 151, 20))
        self.wrong_cred_label_1of2.setStyleSheet("QLabel {\n"
"    color:red;\n"
"}")
        self.wrong_cred_label_1of2.setObjectName("wrong_cred_label_1of2")
        self.p1of2_login_button = QtWidgets.QPushButton(self.player1of2_login_stacked)
        self.p1of2_login_button.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.p1of2_login_button.setStyleSheet("QPushButton{\n"
"    \n"
"    image: url(:/newPrefix/images/edit.png);\n"
"}")
        self.p1of2_login_button.setText("")
        self.p1of2_login_button.setObjectName("p1of2_login_button")
        self.player1of2_stacked.addWidget(self.player1of2_login_stacked)
        self.player2of2_login_frame = QtWidgets.QFrame(self.players2_frame)
        self.player2of2_login_frame.setGeometry(QtCore.QRect(260, 140, 201, 161))
        self.player2of2_login_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(149, 115, 198);\n"
"border-radius: 15;\n"
"}\n"
"\n"
"")
        self.player2of2_login_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.player2of2_login_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.player2of2_login_frame.setObjectName("player2of2_login_frame")
        self.player2of2_stacked = QtWidgets.QStackedWidget(self.player2of2_login_frame)
        self.player2of2_stacked.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.player2of2_stacked.setObjectName("player2of2_stacked")
        self.player2of2_login_stacked = QtWidgets.QWidget()
        self.player2of2_login_stacked.setObjectName("player2of2_login_stacked")
        self.label_7 = QtWidgets.QLabel(self.player2of2_login_stacked)
        self.label_7.setGeometry(QtCore.QRect(65, 10, 58, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.label_7.setObjectName("label_7")
        self.player_icon_label_5 = QtWidgets.QLabel(self.player2of2_login_stacked)
        self.player_icon_label_5.setGeometry(QtCore.QRect(10, 5, 41, 31))
        self.player_icon_label_5.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_5.setText("")
        self.player_icon_label_5.setObjectName("player_icon_label_5")
        self.p2of2_pass = QtWidgets.QLineEdit(self.player2of2_login_stacked)
        self.p2of2_pass.setGeometry(QtCore.QRect(50, 80, 113, 21))
        self.p2of2_pass.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(63, 48, 84);\n"
"lineedit-password-character: 9679;\n"
"}")
        self.p2of2_pass.setObjectName("p2of2_pass")
        self.p2of2_login = QtWidgets.QLineEdit(self.player2of2_login_stacked)
        self.p2of2_login.setGeometry(QtCore.QRect(50, 50, 113, 21))
        self.p2of2_login.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(63, 48, 84);\n"
"}")
        self.p2of2_login.setObjectName("p2of2_login")
        self.wrong_cred_label_2of2 = QtWidgets.QLabel(self.player2of2_login_stacked)
        self.wrong_cred_label_2of2.setGeometry(QtCore.QRect(20, 110, 151, 20))
        self.wrong_cred_label_2of2.setStyleSheet("QLabel {\n"
"    color:red;\n"
"}")
        self.wrong_cred_label_2of2.setObjectName("wrong_cred_label_2of2")
        self.p2of2_login_button = QtWidgets.QPushButton(self.player2of2_login_stacked)
        self.p2of2_login_button.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.p2of2_login_button.setStyleSheet("QPushButton{\n"
"    \n"
"    image: url(:/newPrefix/images/edit.png);\n"
"}")
        self.p2of2_login_button.setText("")
        self.p2of2_login_button.setObjectName("p2of2_login_button")
        self.player2of2_stacked.addWidget(self.player2of2_login_stacked)
        self.player2of2_logged_stacked = QtWidgets.QWidget()
        self.player2of2_logged_stacked.setObjectName("player2of2_logged_stacked")
        self.player_icon_label_11 = QtWidgets.QLabel(self.player2of2_logged_stacked)
        self.player_icon_label_11.setGeometry(QtCore.QRect(30, 40, 41, 31))
        self.player_icon_label_11.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_11.setText("")
        self.player_icon_label_11.setObjectName("player_icon_label_11")
        self.correct_cred_label_5 = QtWidgets.QLabel(self.player2of2_logged_stacked)
        self.correct_cred_label_5.setGeometry(QtCore.QRect(30, 80, 151, 20))
        self.correct_cred_label_5.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(62, 232, 41);\n"
"}")
        self.correct_cred_label_5.setObjectName("correct_cred_label_5")
        self.player2of2_name_label = QtWidgets.QLabel(self.player2of2_logged_stacked)
        self.player2of2_name_label.setGeometry(QtCore.QRect(90, 45, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.player2of2_name_label.setFont(font)
        self.player2of2_name_label.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.player2of2_name_label.setObjectName("player2of2_name_label")
        self.player2of2_stacked.addWidget(self.player2of2_logged_stacked)
        self.login_stacked_widget.addWidget(self.players2_page)
        self.players3_page = QtWidgets.QWidget()
        self.players3_page.setStyleSheet("QFrame {\n"
"    background-color: transparent;\n"
"}")
        self.players3_page.setObjectName("players3_page")
        self.players3_frame = QtWidgets.QFrame(self.players3_page)
        self.players3_frame.setGeometry(QtCore.QRect(10, 0, 501, 331))
        self.players3_frame.setStyleSheet("QFrame {\n"
"    background-color: transparent;\n"
"}")
        self.players3_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.players3_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.players3_frame.setObjectName("players3_frame")
        self.player1of3_login_frame = QtWidgets.QFrame(self.players3_frame)
        self.player1of3_login_frame.setGeometry(QtCore.QRect(30, 10, 201, 161))
        self.player1of3_login_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 78, 131);\n"
"border-radius: 15;\n"
"}\n"
"\n"
"")
        self.player1of3_login_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.player1of3_login_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.player1of3_login_frame.setObjectName("player1of3_login_frame")
        self.player1of3_stacked = QtWidgets.QStackedWidget(self.player1of3_login_frame)
        self.player1of3_stacked.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.player1of3_stacked.setObjectName("player1of3_stacked")
        self.player1of3_logged_stacked = QtWidgets.QWidget()
        self.player1of3_logged_stacked.setObjectName("player1of3_logged_stacked")
        self.player_icon_label_7 = QtWidgets.QLabel(self.player1of3_logged_stacked)
        self.player_icon_label_7.setGeometry(QtCore.QRect(20, 40, 41, 31))
        self.player_icon_label_7.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_7.setText("")
        self.player_icon_label_7.setObjectName("player_icon_label_7")
        self.player1of3_name_label = QtWidgets.QLabel(self.player1of3_logged_stacked)
        self.player1of3_name_label.setGeometry(QtCore.QRect(80, 45, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.player1of3_name_label.setFont(font)
        self.player1of3_name_label.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.player1of3_name_label.setObjectName("player1of3_name_label")
        self.correct_cred_label = QtWidgets.QLabel(self.player1of3_logged_stacked)
        self.correct_cred_label.setGeometry(QtCore.QRect(20, 80, 151, 20))
        self.correct_cred_label.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(62, 232, 41);\n"
"}")
        self.correct_cred_label.setObjectName("correct_cred_label")
        self.player1of3_stacked.addWidget(self.player1of3_logged_stacked)
        self.player1of3_login_stacked = QtWidgets.QWidget()
        self.player1of3_login_stacked.setObjectName("player1of3_login_stacked")
        self.label_2 = QtWidgets.QLabel(self.player1of3_login_stacked)
        self.label_2.setGeometry(QtCore.QRect(55, 10, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.player_icon_label = QtWidgets.QLabel(self.player1of3_login_stacked)
        self.player_icon_label.setGeometry(QtCore.QRect(10, 5, 41, 31))
        self.player_icon_label.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label.setText("")
        self.player_icon_label.setObjectName("player_icon_label")
        self.p1of3_login = QtWidgets.QLineEdit(self.player1of3_login_stacked)
        self.p1of3_login.setGeometry(QtCore.QRect(50, 50, 113, 21))
        self.p1of3_login.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(52, 40, 70);\n"
"}")
        self.p1of3_login.setObjectName("p1of3_login")
        self.p1of3_pass = QtWidgets.QLineEdit(self.player1of3_login_stacked)
        self.p1of3_pass.setGeometry(QtCore.QRect(50, 80, 113, 21))
        self.p1of3_pass.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(52, 40, 70);\n"
"lineedit-password-character: 9679;\n"
"}")
        self.p1of3_pass.setObjectName("p1of3_pass")
        self.wrong_cred_label_1of3 = QtWidgets.QLabel(self.player1of3_login_stacked)
        self.wrong_cred_label_1of3.setGeometry(QtCore.QRect(20, 110, 151, 20))
        self.wrong_cred_label_1of3.setStyleSheet("QLabel {\n"
"    color:red;\n"
"}")
        self.wrong_cred_label_1of3.setObjectName("wrong_cred_label_1of3")
        self.p1of3_login_button = QtWidgets.QPushButton(self.player1of3_login_stacked)
        self.p1of3_login_button.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.p1of3_login_button.setStyleSheet("QPushButton{\n"
"    \n"
"    image: url(:/newPrefix/images/edit.png);\n"
"}")
        self.p1of3_login_button.setText("")
        self.p1of3_login_button.setObjectName("p1of3_login_button")
        self.player1of3_stacked.addWidget(self.player1of3_login_stacked)
        self.player2of3_login_frame = QtWidgets.QFrame(self.players3_frame)
        self.player2of3_login_frame.setGeometry(QtCore.QRect(270, 141, 201, 161))
        self.player2of3_login_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(149, 115, 198);\n"
"border-radius: 15;\n"
"}\n"
"\n"
"")
        self.player2of3_login_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.player2of3_login_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.player2of3_login_frame.setObjectName("player2of3_login_frame")
        self.player2of3_stacked = QtWidgets.QStackedWidget(self.player2of3_login_frame)
        self.player2of3_stacked.setGeometry(QtCore.QRect(10, 9, 181, 141))
        self.player2of3_stacked.setObjectName("player2of3_stacked")
        self.player2of3_login_stacked = QtWidgets.QWidget()
        self.player2of3_login_stacked.setObjectName("player2of3_login_stacked")
        self.label_4 = QtWidgets.QLabel(self.player2of3_login_stacked)
        self.label_4.setGeometry(QtCore.QRect(65, 10, 58, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.player_icon_label_3 = QtWidgets.QLabel(self.player2of3_login_stacked)
        self.player_icon_label_3.setGeometry(QtCore.QRect(10, 5, 41, 31))
        self.player_icon_label_3.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_3.setText("")
        self.player_icon_label_3.setObjectName("player_icon_label_3")
        self.p2of3_pass = QtWidgets.QLineEdit(self.player2of3_login_stacked)
        self.p2of3_pass.setGeometry(QtCore.QRect(50, 80, 113, 21))
        self.p2of3_pass.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(63, 48, 84);\n"
"lineedit-password-character: 9679;\n"
"}")
        self.p2of3_pass.setObjectName("p2of3_pass")
        self.p2of3_login = QtWidgets.QLineEdit(self.player2of3_login_stacked)
        self.p2of3_login.setGeometry(QtCore.QRect(50, 50, 113, 21))
        self.p2of3_login.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(63, 48, 84);\n"
"}")
        self.p2of3_login.setObjectName("p2of3_login")
        self.wrong_cred_label_2of3 = QtWidgets.QLabel(self.player2of3_login_stacked)
        self.wrong_cred_label_2of3.setGeometry(QtCore.QRect(20, 110, 151, 20))
        self.wrong_cred_label_2of3.setStyleSheet("QLabel {\n"
"    color:red;\n"
"}")
        self.wrong_cred_label_2of3.setObjectName("wrong_cred_label_2of3")
        self.p2of3_login_button = QtWidgets.QPushButton(self.player2of3_login_stacked)
        self.p2of3_login_button.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.p2of3_login_button.setStyleSheet("QPushButton{\n"
"    \n"
"    image: url(:/newPrefix/images/edit.png);\n"
"}")
        self.p2of3_login_button.setText("")
        self.p2of3_login_button.setObjectName("p2of3_login_button")
        self.player2of3_stacked.addWidget(self.player2of3_login_stacked)
        self.player2of3_logged_stacked = QtWidgets.QWidget()
        self.player2of3_logged_stacked.setObjectName("player2of3_logged_stacked")
        self.player2of3_name_label = QtWidgets.QLabel(self.player2of3_logged_stacked)
        self.player2of3_name_label.setGeometry(QtCore.QRect(80, 50, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.player2of3_name_label.setFont(font)
        self.player2of3_name_label.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.player2of3_name_label.setObjectName("player2of3_name_label")
        self.player_icon_label_8 = QtWidgets.QLabel(self.player2of3_logged_stacked)
        self.player_icon_label_8.setGeometry(QtCore.QRect(20, 45, 41, 31))
        self.player_icon_label_8.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_8.setText("")
        self.player_icon_label_8.setObjectName("player_icon_label_8")
        self.correct_cred_label_2 = QtWidgets.QLabel(self.player2of3_logged_stacked)
        self.correct_cred_label_2.setGeometry(QtCore.QRect(20, 85, 151, 20))
        self.correct_cred_label_2.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(62, 232, 41);\n"
"}")
        self.correct_cred_label_2.setObjectName("correct_cred_label_2")
        self.player2of3_stacked.addWidget(self.player2of3_logged_stacked)
        self.player3of3_login_frame = QtWidgets.QFrame(self.players3_frame)
        self.player3of3_login_frame.setGeometry(QtCore.QRect(30, 190, 201, 131))
        self.player3of3_login_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(115, 71, 103);\n"
"border-radius: 15;\n"
"}\n"
"\n"
"")
        self.player3of3_login_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.player3of3_login_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.player3of3_login_frame.setObjectName("player3of3_login_frame")
        self.player3of3_stacked = QtWidgets.QStackedWidget(self.player3of3_login_frame)
        self.player3of3_stacked.setGeometry(QtCore.QRect(10, 10, 181, 111))
        self.player3of3_stacked.setObjectName("player3of3_stacked")
        self.player3of3_login_stacked = QtWidgets.QWidget()
        self.player3of3_login_stacked.setObjectName("player3of3_login_stacked")
        self.label_3 = QtWidgets.QLabel(self.player3of3_login_stacked)
        self.label_3.setGeometry(QtCore.QRect(65, 10, 58, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.player_icon_label_2 = QtWidgets.QLabel(self.player3of3_login_stacked)
        self.player_icon_label_2.setGeometry(QtCore.QRect(10, 5, 41, 31))
        self.player_icon_label_2.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_2.setText("")
        self.player_icon_label_2.setObjectName("player_icon_label_2")
        self.p3of3_pass = QtWidgets.QLineEdit(self.player3of3_login_stacked)
        self.p3of3_pass.setGeometry(QtCore.QRect(50, 60, 113, 21))
        self.p3of3_pass.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(69, 43, 63);\n"
"lineedit-password-character: 9679;\n"
"}")
        self.p3of3_pass.setObjectName("p3of3_pass")
        self.p3of3_login = QtWidgets.QLineEdit(self.player3of3_login_stacked)
        self.p3of3_login.setGeometry(QtCore.QRect(50, 30, 113, 21))
        self.p3of3_login.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(69, 43, 63);\n"
"}")
        self.p3of3_login.setObjectName("p3of3_login")
        self.wrong_cred_label_3of3 = QtWidgets.QLabel(self.player3of3_login_stacked)
        self.wrong_cred_label_3of3.setGeometry(QtCore.QRect(20, 90, 151, 20))
        self.wrong_cred_label_3of3.setStyleSheet("QLabel {\n"
"    color:red;\n"
"}")
        self.wrong_cred_label_3of3.setObjectName("wrong_cred_label_3of3")
        self.p3of3_login_button = QtWidgets.QPushButton(self.player3of3_login_stacked)
        self.p3of3_login_button.setGeometry(QtCore.QRect(10, 40, 31, 31))
        self.p3of3_login_button.setStyleSheet("QPushButton{\n"
"    \n"
"    image: url(:/newPrefix/images/edit.png);\n"
"}")
        self.p3of3_login_button.setText("")
        self.p3of3_login_button.setObjectName("p3of3_login_button")
        self.player3of3_stacked.addWidget(self.player3of3_login_stacked)
        self.player3of3_logged_stacked = QtWidgets.QWidget()
        self.player3of3_logged_stacked.setObjectName("player3of3_logged_stacked")
        self.player_icon_label_9 = QtWidgets.QLabel(self.player3of3_logged_stacked)
        self.player_icon_label_9.setGeometry(QtCore.QRect(30, 30, 41, 31))
        self.player_icon_label_9.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_9.setText("")
        self.player_icon_label_9.setObjectName("player_icon_label_9")
        self.correct_cred_label_3 = QtWidgets.QLabel(self.player3of3_logged_stacked)
        self.correct_cred_label_3.setGeometry(QtCore.QRect(30, 70, 151, 20))
        self.correct_cred_label_3.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(62, 232, 41);\n"
"}")
        self.correct_cred_label_3.setObjectName("correct_cred_label_3")
        self.player3of3_name_label = QtWidgets.QLabel(self.player3of3_logged_stacked)
        self.player3of3_name_label.setGeometry(QtCore.QRect(90, 35, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.player3of3_name_label.setFont(font)
        self.player3of3_name_label.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.player3of3_name_label.setObjectName("player3of3_name_label")
        self.player3of3_stacked.addWidget(self.player3of3_logged_stacked)
        self.login_stacked_widget.addWidget(self.players3_page)
        self.players4_page = QtWidgets.QWidget()
        self.players4_page.setObjectName("players4_page")
        self.players4_frame = QtWidgets.QFrame(self.players4_page)
        self.players4_frame.setGeometry(QtCore.QRect(10, 0, 501, 331))
        self.players4_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.players4_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.players4_frame.setObjectName("players4_frame")
        self.player3of4_login_frame = QtWidgets.QFrame(self.players4_frame)
        self.player3of4_login_frame.setGeometry(QtCore.QRect(30, 189, 201, 131))
        self.player3of4_login_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(115, 71, 103);\n"
"border-radius: 15;\n"
"}\n"
"\n"
"")
        self.player3of4_login_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.player3of4_login_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.player3of4_login_frame.setObjectName("player3of4_login_frame")
        self.player3of4_stacked = QtWidgets.QStackedWidget(self.player3of4_login_frame)
        self.player3of4_stacked.setGeometry(QtCore.QRect(10, 10, 181, 111))
        self.player3of4_stacked.setObjectName("player3of4_stacked")
        self.player3of4_login_stacked = QtWidgets.QWidget()
        self.player3of4_login_stacked.setObjectName("player3of4_login_stacked")
        self.label_9 = QtWidgets.QLabel(self.player3of4_login_stacked)
        self.label_9.setGeometry(QtCore.QRect(65, 10, 58, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.label_9.setObjectName("label_9")
        self.player_icon_label_12 = QtWidgets.QLabel(self.player3of4_login_stacked)
        self.player_icon_label_12.setGeometry(QtCore.QRect(10, 5, 41, 31))
        self.player_icon_label_12.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_12.setText("")
        self.player_icon_label_12.setObjectName("player_icon_label_12")
        self.p3of4_pass = QtWidgets.QLineEdit(self.player3of4_login_stacked)
        self.p3of4_pass.setGeometry(QtCore.QRect(50, 60, 113, 21))
        self.p3of4_pass.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(69, 43, 63);\n"
"lineedit-password-character: 9679;\n"
"}")
        self.p3of4_pass.setObjectName("p3of4_pass")
        self.p3of4_login = QtWidgets.QLineEdit(self.player3of4_login_stacked)
        self.p3of4_login.setGeometry(QtCore.QRect(50, 30, 113, 21))
        self.p3of4_login.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(69, 43, 63);\n"
"}")
        self.p3of4_login.setObjectName("p3of4_login")
        self.wrong_cred_label_3of4 = QtWidgets.QLabel(self.player3of4_login_stacked)
        self.wrong_cred_label_3of4.setGeometry(QtCore.QRect(20, 90, 151, 20))
        self.wrong_cred_label_3of4.setStyleSheet("QLabel {\n"
"    color:red;\n"
"}")
        self.wrong_cred_label_3of4.setObjectName("wrong_cred_label_3of4")
        self.p3of4_login_button = QtWidgets.QPushButton(self.player3of4_login_stacked)
        self.p3of4_login_button.setGeometry(QtCore.QRect(10, 40, 31, 31))
        self.p3of4_login_button.setStyleSheet("QPushButton{\n"
"    \n"
"    image: url(:/newPrefix/images/edit.png);\n"
"}")
        self.p3of4_login_button.setText("")
        self.p3of4_login_button.setObjectName("p3of4_login_button")
        self.player3of4_stacked.addWidget(self.player3of4_login_stacked)
        self.player3of4_logged_stacked = QtWidgets.QWidget()
        self.player3of4_logged_stacked.setObjectName("player3of4_logged_stacked")
        self.player_icon_label_13 = QtWidgets.QLabel(self.player3of4_logged_stacked)
        self.player_icon_label_13.setGeometry(QtCore.QRect(30, 30, 41, 31))
        self.player_icon_label_13.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_13.setText("")
        self.player_icon_label_13.setObjectName("player_icon_label_13")
        self.correct_cred_label_6 = QtWidgets.QLabel(self.player3of4_logged_stacked)
        self.correct_cred_label_6.setGeometry(QtCore.QRect(30, 70, 151, 20))
        self.correct_cred_label_6.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(62, 232, 41);\n"
"}")
        self.correct_cred_label_6.setObjectName("correct_cred_label_6")
        self.player3of4_name_label = QtWidgets.QLabel(self.player3of4_logged_stacked)
        self.player3of4_name_label.setGeometry(QtCore.QRect(90, 35, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.player3of4_name_label.setFont(font)
        self.player3of4_name_label.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.player3of4_name_label.setObjectName("player3of4_name_label")
        self.player3of4_stacked.addWidget(self.player3of4_logged_stacked)
        self.player1of4_login_frame = QtWidgets.QFrame(self.players4_frame)
        self.player1of4_login_frame.setGeometry(QtCore.QRect(30, 9, 201, 161))
        self.player1of4_login_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(99, 78, 131);\n"
"border-radius: 15;\n"
"}\n"
"\n"
"")
        self.player1of4_login_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.player1of4_login_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.player1of4_login_frame.setObjectName("player1of4_login_frame")
        self.player1of4_stacked = QtWidgets.QStackedWidget(self.player1of4_login_frame)
        self.player1of4_stacked.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.player1of4_stacked.setObjectName("player1of4_stacked")
        self.player1of4_logged_stacked = QtWidgets.QWidget()
        self.player1of4_logged_stacked.setObjectName("player1of4_logged_stacked")
        self.player_icon_label_14 = QtWidgets.QLabel(self.player1of4_logged_stacked)
        self.player_icon_label_14.setGeometry(QtCore.QRect(20, 40, 41, 31))
        self.player_icon_label_14.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_14.setText("")
        self.player_icon_label_14.setObjectName("player_icon_label_14")
        self.player1of4_name_label = QtWidgets.QLabel(self.player1of4_logged_stacked)
        self.player1of4_name_label.setGeometry(QtCore.QRect(80, 45, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.player1of4_name_label.setFont(font)
        self.player1of4_name_label.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.player1of4_name_label.setObjectName("player1of4_name_label")
        self.correct_cred_label_7 = QtWidgets.QLabel(self.player1of4_logged_stacked)
        self.correct_cred_label_7.setGeometry(QtCore.QRect(20, 80, 151, 20))
        self.correct_cred_label_7.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(62, 232, 41);\n"
"}")
        self.correct_cred_label_7.setObjectName("correct_cred_label_7")
        self.player1of4_stacked.addWidget(self.player1of4_logged_stacked)
        self.player1of4_login_stacked = QtWidgets.QWidget()
        self.player1of4_login_stacked.setObjectName("player1of4_login_stacked")
        self.label_10 = QtWidgets.QLabel(self.player1of4_login_stacked)
        self.label_10.setGeometry(QtCore.QRect(55, 10, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.label_10.setObjectName("label_10")
        self.player_icon_label_15 = QtWidgets.QLabel(self.player1of4_login_stacked)
        self.player_icon_label_15.setGeometry(QtCore.QRect(10, 5, 41, 31))
        self.player_icon_label_15.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_15.setText("")
        self.player_icon_label_15.setObjectName("player_icon_label_15")
        self.p1of4_login = QtWidgets.QLineEdit(self.player1of4_login_stacked)
        self.p1of4_login.setGeometry(QtCore.QRect(50, 50, 113, 21))
        self.p1of4_login.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(52, 40, 70);\n"
"}")
        self.p1of4_login.setObjectName("p1of4_login")
        self.p1of4_pass = QtWidgets.QLineEdit(self.player1of4_login_stacked)
        self.p1of4_pass.setGeometry(QtCore.QRect(50, 80, 113, 21))
        self.p1of4_pass.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(52, 40, 70);\n"
"lineedit-password-character: 9679;\n"
"}")
        self.p1of4_pass.setObjectName("p1of4_pass")
        self.wrong_cred_labe_1of4 = QtWidgets.QLabel(self.player1of4_login_stacked)
        self.wrong_cred_labe_1of4.setGeometry(QtCore.QRect(20, 110, 151, 20))
        self.wrong_cred_labe_1of4.setStyleSheet("QLabel {\n"
"    color:red;\n"
"}")
        self.wrong_cred_labe_1of4.setObjectName("wrong_cred_labe_1of4")
        self.p1of4_login_button = QtWidgets.QPushButton(self.player1of4_login_stacked)
        self.p1of4_login_button.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.p1of4_login_button.setStyleSheet("QPushButton{\n"
"    \n"
"    image: url(:/newPrefix/images/edit.png);\n"
"}")
        self.p1of4_login_button.setText("")
        self.p1of4_login_button.setObjectName("p1of4_login_button")
        self.player1of4_stacked.addWidget(self.player1of4_login_stacked)
        self.player2of4_login_frame = QtWidgets.QFrame(self.players4_frame)
        self.player2of4_login_frame.setGeometry(QtCore.QRect(270, 160, 201, 161))
        self.player2of4_login_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(149, 115, 198);\n"
"border-radius: 15;\n"
"}\n"
"\n"
"")
        self.player2of4_login_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.player2of4_login_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.player2of4_login_frame.setObjectName("player2of4_login_frame")
        self.player2of4_stacked = QtWidgets.QStackedWidget(self.player2of4_login_frame)
        self.player2of4_stacked.setGeometry(QtCore.QRect(10, 9, 181, 141))
        self.player2of4_stacked.setObjectName("player2of4_stacked")
        self.player2of4_login_stacked = QtWidgets.QWidget()
        self.player2of4_login_stacked.setObjectName("player2of4_login_stacked")
        self.label_11 = QtWidgets.QLabel(self.player2of4_login_stacked)
        self.label_11.setGeometry(QtCore.QRect(65, 10, 58, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.label_11.setObjectName("label_11")
        self.player_icon_label_16 = QtWidgets.QLabel(self.player2of4_login_stacked)
        self.player_icon_label_16.setGeometry(QtCore.QRect(10, 5, 41, 31))
        self.player_icon_label_16.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_16.setText("")
        self.player_icon_label_16.setObjectName("player_icon_label_16")
        self.p2of4_pass = QtWidgets.QLineEdit(self.player2of4_login_stacked)
        self.p2of4_pass.setGeometry(QtCore.QRect(50, 80, 113, 21))
        self.p2of4_pass.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(63, 48, 84);\n"
"lineedit-password-character: 9679;\n"
"}")
        self.p2of4_pass.setObjectName("p2of4_pass")
        self.p2of4_login = QtWidgets.QLineEdit(self.player2of4_login_stacked)
        self.p2of4_login.setGeometry(QtCore.QRect(50, 50, 113, 21))
        self.p2of4_login.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(63, 48, 84);\n"
"}")
        self.p2of4_login.setObjectName("p2of4_login")
        self.wrong_cred_label_2of4 = QtWidgets.QLabel(self.player2of4_login_stacked)
        self.wrong_cred_label_2of4.setGeometry(QtCore.QRect(20, 110, 151, 20))
        self.wrong_cred_label_2of4.setStyleSheet("QLabel {\n"
"    color:red;\n"
"}")
        self.wrong_cred_label_2of4.setObjectName("wrong_cred_label_2of4")
        self.p2of4_login_button = QtWidgets.QPushButton(self.player2of4_login_stacked)
        self.p2of4_login_button.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.p2of4_login_button.setStyleSheet("QPushButton{\n"
"    \n"
"    image: url(:/newPrefix/images/edit.png);\n"
"}")
        self.p2of4_login_button.setText("")
        self.p2of4_login_button.setObjectName("p2of4_login_button")
        self.player2of4_stacked.addWidget(self.player2of4_login_stacked)
        self.player2of4_logged_stacked = QtWidgets.QWidget()
        self.player2of4_logged_stacked.setObjectName("player2of4_logged_stacked")
        self.player2of4_name_label = QtWidgets.QLabel(self.player2of4_logged_stacked)
        self.player2of4_name_label.setGeometry(QtCore.QRect(80, 50, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.player2of4_name_label.setFont(font)
        self.player2of4_name_label.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.player2of4_name_label.setObjectName("player2of4_name_label")
        self.player_icon_label_17 = QtWidgets.QLabel(self.player2of4_logged_stacked)
        self.player_icon_label_17.setGeometry(QtCore.QRect(20, 45, 41, 31))
        self.player_icon_label_17.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_17.setText("")
        self.player_icon_label_17.setObjectName("player_icon_label_17")
        self.correct_cred_label_8 = QtWidgets.QLabel(self.player2of4_logged_stacked)
        self.correct_cred_label_8.setGeometry(QtCore.QRect(20, 85, 151, 20))
        self.correct_cred_label_8.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(62, 232, 41);\n"
"}")
        self.correct_cred_label_8.setObjectName("correct_cred_label_8")
        self.player2of4_stacked.addWidget(self.player2of4_logged_stacked)
        self.player4of4_login_frame = QtWidgets.QFrame(self.players4_frame)
        self.player4of4_login_frame.setGeometry(QtCore.QRect(270, 10, 201, 131))
        self.player4of4_login_frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(151, 92, 138);\n"
"border-radius: 15;\n"
"}\n"
"\n"
"")
        self.player4of4_login_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.player4of4_login_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.player4of4_login_frame.setObjectName("player4of4_login_frame")
        self.player4of4_stacked = QtWidgets.QStackedWidget(self.player4of4_login_frame)
        self.player4of4_stacked.setGeometry(QtCore.QRect(10, 10, 181, 111))
        self.player4of4_stacked.setObjectName("player4of4_stacked")
        self.player4of4_login_stacked = QtWidgets.QWidget()
        self.player4of4_login_stacked.setObjectName("player4of4_login_stacked")
        self.label_12 = QtWidgets.QLabel(self.player4of4_login_stacked)
        self.label_12.setGeometry(QtCore.QRect(65, 10, 58, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.label_12.setObjectName("label_12")
        self.player_icon_label_18 = QtWidgets.QLabel(self.player4of4_login_stacked)
        self.player_icon_label_18.setGeometry(QtCore.QRect(10, 5, 41, 31))
        self.player_icon_label_18.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_18.setText("")
        self.player_icon_label_18.setObjectName("player_icon_label_18")
        self.p4of4_pass = QtWidgets.QLineEdit(self.player4of4_login_stacked)
        self.p4of4_pass.setGeometry(QtCore.QRect(50, 60, 113, 21))
        self.p4of4_pass.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(69, 43, 63);\n"
"lineedit-password-character: 9679;\n"
"}")
        self.p4of4_pass.setObjectName("p4of4_pass")
        self.p4of4_login = QtWidgets.QLineEdit(self.player4of4_login_stacked)
        self.p4of4_login.setGeometry(QtCore.QRect(50, 30, 113, 21))
        self.p4of4_login.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: rgb(69, 43, 63);\n"
"}")
        self.p4of4_login.setObjectName("p4of4_login")
        self.wrong_cred_label_4of4 = QtWidgets.QLabel(self.player4of4_login_stacked)
        self.wrong_cred_label_4of4.setGeometry(QtCore.QRect(20, 90, 151, 20))
        self.wrong_cred_label_4of4.setStyleSheet("QLabel {\n"
"    color:red;\n"
"}")
        self.wrong_cred_label_4of4.setObjectName("wrong_cred_label_4of4")
        self.p4of4_login_button = QtWidgets.QPushButton(self.player4of4_login_stacked)
        self.p4of4_login_button.setGeometry(QtCore.QRect(10, 40, 31, 31))
        self.p4of4_login_button.setStyleSheet("QPushButton{\n"
"    \n"
"    image: url(:/newPrefix/images/edit.png);\n"
"}")
        self.p4of4_login_button.setText("")
        self.p4of4_login_button.setObjectName("p4of4_login_button")
        self.player4of4_stacked.addWidget(self.player4of4_login_stacked)
        self.player4of4_logged_stacked = QtWidgets.QWidget()
        self.player4of4_logged_stacked.setObjectName("player4of4_logged_stacked")
        self.player_icon_label_19 = QtWidgets.QLabel(self.player4of4_logged_stacked)
        self.player_icon_label_19.setGeometry(QtCore.QRect(30, 30, 41, 31))
        self.player_icon_label_19.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.player_icon_label_19.setText("")
        self.player_icon_label_19.setObjectName("player_icon_label_19")
        self.correct_cred_label_9 = QtWidgets.QLabel(self.player4of4_logged_stacked)
        self.correct_cred_label_9.setGeometry(QtCore.QRect(30, 70, 151, 20))
        self.correct_cred_label_9.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(62, 232, 41);\n"
"}")
        self.correct_cred_label_9.setObjectName("correct_cred_label_9")
        self.player4of4_name_label = QtWidgets.QLabel(self.player4of4_logged_stacked)
        self.player4of4_name_label.setGeometry(QtCore.QRect(90, 35, 91, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        self.player4of4_name_label.setFont(font)
        self.player4of4_name_label.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.player4of4_name_label.setObjectName("player4of4_name_label")
        self.player4of4_stacked.addWidget(self.player4of4_logged_stacked)
        self.login_stacked_widget.addWidget(self.players4_page)
        self.label = QtWidgets.QLabel(self.menu_frame)
        self.label.setGeometry(QtCore.QRect(60, 215, 171, 21))
        self.label.setStyleSheet("QLabel{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.label.setObjectName("label")
        self.start_game_label = QtWidgets.QLabel(self.menu_frame)
        self.start_game_label.setGeometry(QtCore.QRect(390, 170, 131, 41))
        self.start_game_label.setStyleSheet("QLabel {\n"
"    color: rgb(204, 205, 143);\n"
"}")
        self.start_game_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.start_game_label.setObjectName("start_game_label")
        self.start_game_button = QtWidgets.QPushButton(self.menu_frame)
        self.start_game_button.setGeometry(QtCore.QRect(420, 121, 71, 51))
        self.start_game_button.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    image: url(:/newPrefix/images/swords.png);\n"
"}")
        self.start_game_button.setText("")
        self.start_game_button.setObjectName("start_game_button")
        self.start_game_status_label = QtWidgets.QLabel(self.menu_frame)
        self.start_game_status_label.setGeometry(QtCore.QRect(340, 80, 231, 41))
        self.start_game_status_label.setStyleSheet("QLabel {\n"
"    color: red;\n"
"}")
        self.start_game_status_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.start_game_status_label.setObjectName("start_game_status_label")
        hotseat_players_login_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(hotseat_players_login_window)
        self.login_stacked_widget.setCurrentIndex(2)
        self.player1of2_stacked.setCurrentIndex(1)
        self.player2of2_stacked.setCurrentIndex(0)
        self.player1of3_stacked.setCurrentIndex(1)
        self.player2of3_stacked.setCurrentIndex(0)
        self.player3of3_stacked.setCurrentIndex(0)
        self.player3of4_stacked.setCurrentIndex(0)
        self.player1of4_stacked.setCurrentIndex(1)
        self.player2of4_stacked.setCurrentIndex(0)
        self.player4of4_stacked.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(hotseat_players_login_window)

    def retranslateUi(self, hotseat_players_login_window):
        _translate = QtCore.QCoreApplication.translate
        hotseat_players_login_window.setWindowTitle(_translate("hotseat_players_login_window", "MainWindow"))
        self.name_label.setText(_translate("hotseat_players_login_window", "<html><head/><body><p><span style=\" font-weight:700;\">Scrabble</span></p><p><br/></p></body></html>"))
        self.game_mode_label.setText(_translate("hotseat_players_login_window", "<html><head/><body><p><span style=\" font-size:18pt;\">Tryb gry</span></p></body></html>"))
        self.hotseat_mode_label.setText(_translate("hotseat_players_login_window", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:700; font-style:italic;\">hot seat</span></p></body></html>"))
        self.correct_cred_label_4.setText(_translate("hotseat_players_login_window", "poprawnie zalogowano"))
        self.player1of2_name_label.setText(_translate("hotseat_players_login_window", "gracz 1."))
        self.label_6.setText(_translate("hotseat_players_login_window", "gracz 1."))
        self.wrong_cred_label_1of2.setText(_translate("hotseat_players_login_window", "wprowadzono złe dane"))
        self.label_7.setText(_translate("hotseat_players_login_window", "gracz 2."))
        self.wrong_cred_label_2of2.setText(_translate("hotseat_players_login_window", "wprowadzono złe dane"))
        self.correct_cred_label_5.setText(_translate("hotseat_players_login_window", "poprawnie zalogowano"))
        self.player2of2_name_label.setText(_translate("hotseat_players_login_window", "gracz 2."))
        self.player1of3_name_label.setText(_translate("hotseat_players_login_window", "gracz 1."))
        self.correct_cred_label.setText(_translate("hotseat_players_login_window", "poprawnie zalogowano"))
        self.label_2.setText(_translate("hotseat_players_login_window", "gracz 1."))
        self.wrong_cred_label_1of3.setText(_translate("hotseat_players_login_window", "wprowadzono złe dane"))
        self.label_4.setText(_translate("hotseat_players_login_window", "gracz 2."))
        self.wrong_cred_label_2of3.setText(_translate("hotseat_players_login_window", "wprowadzono złe dane"))
        self.player2of3_name_label.setText(_translate("hotseat_players_login_window", "gracz 2."))
        self.correct_cred_label_2.setText(_translate("hotseat_players_login_window", "poprawnie zalogowano"))
        self.label_3.setText(_translate("hotseat_players_login_window", "gracz 3."))
        self.wrong_cred_label_3of3.setText(_translate("hotseat_players_login_window", "wprowadzono złe dane"))
        self.correct_cred_label_3.setText(_translate("hotseat_players_login_window", "poprawnie zalogowano"))
        self.player3of3_name_label.setText(_translate("hotseat_players_login_window", "gracz 3."))
        self.label_9.setText(_translate("hotseat_players_login_window", "gracz 3."))
        self.wrong_cred_label_3of4.setText(_translate("hotseat_players_login_window", "wprowadzono złe dane"))
        self.correct_cred_label_6.setText(_translate("hotseat_players_login_window", "poprawnie zalogowano"))
        self.player3of4_name_label.setText(_translate("hotseat_players_login_window", "gracz 3."))
        self.player1of4_name_label.setText(_translate("hotseat_players_login_window", "gracz 1."))
        self.correct_cred_label_7.setText(_translate("hotseat_players_login_window", "poprawnie zalogowano"))
        self.label_10.setText(_translate("hotseat_players_login_window", "gracz 1."))
        self.wrong_cred_labe_1of4.setText(_translate("hotseat_players_login_window", "wprowadzono złe dane"))
        self.label_11.setText(_translate("hotseat_players_login_window", "gracz 2."))
        self.wrong_cred_label_2of4.setText(_translate("hotseat_players_login_window", "wprowadzono złe dane"))
        self.player2of4_name_label.setText(_translate("hotseat_players_login_window", "gracz 2."))
        self.correct_cred_label_8.setText(_translate("hotseat_players_login_window", "poprawnie zalogowano"))
        self.label_12.setText(_translate("hotseat_players_login_window", "gracz 4."))
        self.wrong_cred_label_4of4.setText(_translate("hotseat_players_login_window", "wprowadzono złe dane"))
        self.correct_cred_label_9.setText(_translate("hotseat_players_login_window", "poprawnie zalogowano"))
        self.player4of4_name_label.setText(_translate("hotseat_players_login_window", "gracz 4."))
        self.label.setText(_translate("hotseat_players_login_window", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; font-style:italic;\">Zalogujcie się</span></p></body></html>"))
        self.start_game_label.setText(_translate("hotseat_players_login_window", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; font-style:italic;\">rozpocznij grę</span></p></body></html>"))
        self.start_game_status_label.setText(_translate("hotseat_players_login_window", "<html><head/><body><p>czy wszyscy gracze są zalogowani?</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hotseat_players_login_window = QtWidgets.QMainWindow()
    ui = Ui_hotseat_players_login_window()
    ui.setupUi(hotseat_players_login_window)
    hotseat_players_login_window.show()
    sys.exit(app.exec())
