# Form implementation generated from reading ui file '/Users/mzieba/Documents/szkola/code/Scrabble_with_GUI/templates/hotseat_player_count_window.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_hotseat_player_count_window(object):
    def setupUi(self, hotseat_player_count_window):
        hotseat_player_count_window.setObjectName("hotseat_player_count_window")
        hotseat_player_count_window.resize(600, 650)
        self.centralwidget = QtWidgets.QWidget(hotseat_player_count_window)
        self.centralwidget.setObjectName("centralwidget")
        self.menu_frame = QtWidgets.QFrame(self.centralwidget)
        self.menu_frame.setGeometry(QtCore.QRect(140, 60, 311, 501))
        self.menu_frame.setStyleSheet("QFrame {\n"
"    border-radius: 7px;\n"
"    color: rgb(62, 231, 41);\n"
"    background-color: rgb(40, 109, 50);\n"
"}\n"
"")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.name_label = QtWidgets.QLabel(self.menu_frame)
        self.name_label.setGeometry(QtCore.QRect(-40, 20, 361, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.exit_button = QtWidgets.QPushButton(self.menu_frame)
        self.exit_button.setGeometry(QtCore.QRect(290, 7, 14, 14))
        self.exit_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 40, 54);\n"
"    border-radius: 7px;\n"
"    border: none\n"
"}")
        self.exit_button.setText("")
        self.exit_button.setCheckable(False)
        self.exit_button.setDefault(False)
        self.exit_button.setFlat(False)
        self.exit_button.setObjectName("exit_button")
        self.game_mode_frame = QtWidgets.QFrame(self.menu_frame)
        self.game_mode_frame.setGeometry(QtCore.QRect(40, 110, 231, 321))
        self.game_mode_frame.setStyleSheet("QFrame {\n"
"background-color: rgb(22, 60, 27);\n"
"}\n"
"")
        self.game_mode_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.game_mode_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.game_mode_frame.setObjectName("game_mode_frame")
        self.game_mode_label = QtWidgets.QLabel(self.game_mode_frame)
        self.game_mode_label.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.game_mode_label.setFont(font)
        self.game_mode_label.setStyleSheet("QLabel {\n"
"    color: rgb(226, 224, 158);\n"
"\n"
"}")
        self.game_mode_label.setObjectName("game_mode_label")
        self.hotseat_mode_label = QtWidgets.QLabel(self.game_mode_frame)
        self.hotseat_mode_label.setGeometry(QtCore.QRect(110, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hotseat_mode_label.setFont(font)
        self.hotseat_mode_label.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(62, 232, 41);\n"
"}")
        self.hotseat_mode_label.setObjectName("hotseat_mode_label")
        self.game_mode_desc = QtWidgets.QTextBrowser(self.game_mode_frame)
        self.game_mode_desc.setGeometry(QtCore.QRect(40, 120, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        self.game_mode_desc.setFont(font)
        self.game_mode_desc.setStyleSheet("QWidget{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.game_mode_desc.setObjectName("game_mode_desc")
        self.player_count_label = QtWidgets.QLabel(self.game_mode_frame)
        self.player_count_label.setGeometry(QtCore.QRect(20, 200, 131, 16))
        self.player_count_label.setStyleSheet("QWidget{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.player_count_label.setObjectName("player_count_label")
        self.player2_button = QtWidgets.QPushButton(self.game_mode_frame)
        self.player2_button.setGeometry(QtCore.QRect(20, 250, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.player2_button.setFont(font)
        self.player2_button.setStyleSheet("QPushButton{\n"
"    border-radius: 20;\n"
"    background-color: rgb(202, 78, 68);\n"
"}")
        self.player2_button.setObjectName("player2_button")
        self.player3_button = QtWidgets.QPushButton(self.game_mode_frame)
        self.player3_button.setGeometry(QtCore.QRect(90, 240, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.player3_button.setFont(font)
        self.player3_button.setStyleSheet("QPushButton{\n"
"    border-radius: 20;\n"
"    background-color: rgb(202, 78, 68);\n"
"}")
        self.player3_button.setObjectName("player3_button")
        self.player4_button = QtWidgets.QPushButton(self.game_mode_frame)
        self.player4_button.setGeometry(QtCore.QRect(160, 230, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.player4_button.setFont(font)
        self.player4_button.setStyleSheet("QPushButton{\n"
"    border-radius: 20;\n"
"    background-color: rgb(202, 78, 68);\n"
"}")
        self.player4_button.setObjectName("player4_button")
        self.hotseat_icon_label = QtWidgets.QLabel(self.game_mode_frame)
        self.hotseat_icon_label.setGeometry(QtCore.QRect(40, 65, 61, 41))
        self.hotseat_icon_label.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.hotseat_icon_label.setText("")
        self.hotseat_icon_label.setObjectName("hotseat_icon_label")
        self.return_to_menu_button = QtWidgets.QPushButton(self.menu_frame)
        self.return_to_menu_button.setGeometry(QtCore.QRect(120, 450, 71, 32))
        self.return_to_menu_button.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"image: url(:/newPrefix/images/returnleft.png);\n"
"}\n"
"")
        self.return_to_menu_button.setText("")
        self.return_to_menu_button.setObjectName("return_to_menu_button")
        hotseat_player_count_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(hotseat_player_count_window)
        QtCore.QMetaObject.connectSlotsByName(hotseat_player_count_window)

    def retranslateUi(self, hotseat_player_count_window):
        _translate = QtCore.QCoreApplication.translate
        hotseat_player_count_window.setWindowTitle(_translate("hotseat_player_count_window", "MainWindow"))
        self.name_label.setText(_translate("hotseat_player_count_window", "<html><head/><body><p><span style=\" font-weight:700;\">Scrabble</span></p><p><br/></p></body></html>"))
        self.game_mode_label.setText(_translate("hotseat_player_count_window", "<html><head/><body><p><span style=\" font-size:18pt;\">Tryb gry</span></p></body></html>"))
        self.hotseat_mode_label.setText(_translate("hotseat_player_count_window", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:700; font-style:italic;\">hot seat</span></p></body></html>"))
        self.game_mode_desc.setHtml(_translate("hotseat_player_count_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:14pt; font-weight:700; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13pt;\">w tym trybie rozgrywki zmierzysz się innymi ludźmi</span></p></body></html>"))
        self.player_count_label.setText(_translate("hotseat_player_count_window", "wybierz liczbę graczy"))
        self.player2_button.setText(_translate("hotseat_player_count_window", "2"))
        self.player3_button.setText(_translate("hotseat_player_count_window", "3"))
        self.player4_button.setText(_translate("hotseat_player_count_window", "4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    hotseat_player_count_window = QtWidgets.QMainWindow()
    ui = Ui_hotseat_player_count_window()
    ui.setupUi(hotseat_player_count_window)
    hotseat_player_count_window.show()
    sys.exit(app.exec())
