# Form implementation generated from reading ui file '/Users/mzieba/Documents/szkola/code/Scrabble_with_GUI/templates/login_window.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login_window(object):
    def setupUi(self, login_window):
        login_window.setObjectName("login_window")
        login_window.resize(412, 507)
        self.centralwidget = QtWidgets.QWidget(login_window)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame {\n"
"    border-radius: 7px;\n"
"    color: rgb(62, 231, 41);\n"
"    background-color: rgb(40, 109, 50);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.name_label = QtWidgets.QLabel(self.frame)
        self.name_label.setGeometry(QtCore.QRect(-140, 60, 661, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.exit_button = QtWidgets.QPushButton(self.frame)
        self.exit_button.setGeometry(QtCore.QRect(370, 10, 14, 14))
        self.exit_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 40, 54);\n"
"    border-radius: 7px;\n"
"    border: none\n"
"}")
        self.exit_button.setText("")
        self.exit_button.setCheckable(False)
        self.exit_button.setDefault(False)
        self.exit_button.setFlat(False)
        self.exit_button.setObjectName("exit_button")
        self.emoji_label = QtWidgets.QLabel(self.frame)
        self.emoji_label.setGeometry(QtCore.QRect(110, 340, 151, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.emoji_label.setFont(font)
        self.emoji_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.emoji_label.setObjectName("emoji_label")
        self.login_reg_stacked = QtWidgets.QStackedWidget(self.frame)
        self.login_reg_stacked.setGeometry(QtCore.QRect(80, 150, 251, 181))
        self.login_reg_stacked.setStyleSheet("QWidget{\n"
"    background-color: transparent;\n"
"}")
        self.login_reg_stacked.setObjectName("login_reg_stacked")
        self.login_content = QtWidgets.QWidget()
        self.login_content.setObjectName("login_content")
        self.login_container = QtWidgets.QFrame(self.login_content)
        self.login_container.setGeometry(QtCore.QRect(-10, 10, 251, 171))
        self.login_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.login_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.login_container.setObjectName("login_container")
        self.error_label = QtWidgets.QLabel(self.login_container)
        self.error_label.setGeometry(QtCore.QRect(27, 100, 201, 20))
        self.error_label.setStyleSheet("QLabel {\n"
"    color: red;\n"
"}")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.error_label.setObjectName("error_label")
        self.register_button = QtWidgets.QPushButton(self.login_container)
        self.register_button.setGeometry(QtCore.QRect(40, 130, 81, 31))
        self.register_button.setStyleSheet("QPushButton{\n"
"    color: rgb(206, 202, 207);\n"
"    background-color: rgb(188, 85, 49);\n"
"        border-radius:7px;\n"
"}QPushButton::pressed{\n"
"    background-color: rgb(174, 69, 77);\n"
"}")
        self.register_button.setObjectName("register_button")
        self.password_input = QtWidgets.QLineEdit(self.login_container)
        self.password_input.setGeometry(QtCore.QRect(20, 70, 211, 21))
        self.password_input.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: rgb(206, 202, 207);\n"
"    background-color: rgb(55, 148, 67);\n"
"lineedit-password-character: 9679;\n"
"}")
        self.password_input.setText("")
        self.password_input.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.password_input.setObjectName("password_input")
        self.login_button = QtWidgets.QPushButton(self.login_container)
        self.login_button.setGeometry(QtCore.QRect(130, 130, 81, 31))
        self.login_button.setStyleSheet("QPushButton{\n"
"    color: rgb(206, 202, 207);\n"
"        background-color: rgb(150, 38, 26);\n"
"        border-radius:7px;\n"
"}QPushButton::pressed{\n"
"    background-color: rgb(174, 69, 77);\n"
"}")
        self.login_button.setObjectName("login_button")
        self.login_input = QtWidgets.QLineEdit(self.login_container)
        self.login_input.setGeometry(QtCore.QRect(20, 30, 211, 21))
        self.login_input.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: rgb(206, 202, 207);\n"
"    background-color: rgb(55, 148, 67);\n"
"}")
        self.login_input.setText("")
        self.login_input.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.login_input.setObjectName("login_input")
        self.label_2 = QtWidgets.QLabel(self.login_container)
        self.label_2.setGeometry(QtCore.QRect(70, 0, 121, 20))
        self.label_2.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.login_reg_stacked.addWidget(self.login_content)
        self.register_content = QtWidgets.QWidget()
        self.register_content.setStyleSheet("QFrame {\n"
"    background-color: transparent;\n"
"}")
        self.register_content.setObjectName("register_content")
        self.register_container = QtWidgets.QFrame(self.register_content)
        self.register_container.setGeometry(QtCore.QRect(0, 10, 251, 181))
        self.register_container.setStyleSheet("QFrame {\n"
"    background-color: transparent;\n"
"}")
        self.register_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.register_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.register_container.setObjectName("register_container")
        self.error_register_label = QtWidgets.QLabel(self.register_container)
        self.error_register_label.setGeometry(QtCore.QRect(30, 100, 191, 20))
        self.error_register_label.setStyleSheet("QLabel {\n"
"    color: red;\n"
"}")
        self.error_register_label.setText("")
        self.error_register_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.error_register_label.setObjectName("error_register_label")
        self.init_register_button = QtWidgets.QPushButton(self.register_container)
        self.init_register_button.setGeometry(QtCore.QRect(140, 130, 91, 31))
        self.init_register_button.setStyleSheet("QPushButton{\n"
"    color: rgb(206, 202, 207);\n"
"    background-color: rgb(188, 85, 49);\n"
"        border-radius:7px;\n"
"}QPushButton::pressed{\n"
"    background-color: rgb(174, 69, 77);\n"
"}")
        self.init_register_button.setObjectName("init_register_button")
        self.reg_password_input = QtWidgets.QLineEdit(self.register_container)
        self.reg_password_input.setGeometry(QtCore.QRect(20, 70, 211, 21))
        self.reg_password_input.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: rgb(206, 202, 207);\n"
"    background-color: rgb(55, 148, 67);\n"
"lineedit-password-character: 9679;\n"
"}")
        self.reg_password_input.setText("")
        self.reg_password_input.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.reg_password_input.setObjectName("reg_password_input")
        self.init_login_button = QtWidgets.QPushButton(self.register_container)
        self.init_login_button.setGeometry(QtCore.QRect(30, 130, 91, 31))
        self.init_login_button.setStyleSheet("QPushButton{\n"
"color: rgb(211, 238, 231);\n"
"    background-color: rgb(119, 192, 255);\n"
"        border-radius:7px;\n"
"border: 2px;\n"
"}QPushButton::pressed{\n"
"    border-color: rgb(44, 88, 54);\n"
"    background-color: rgb(174, 69, 77);\n"
"}")
        self.init_login_button.setObjectName("init_login_button")
        self.reg_login_input = QtWidgets.QLineEdit(self.register_container)
        self.reg_login_input.setGeometry(QtCore.QRect(20, 30, 211, 21))
        self.reg_login_input.setStyleSheet("QLineEdit {\n"
"    border-radius: 10px;\n"
"    color: rgb(206, 202, 207);\n"
"    background-color: rgb(55, 148, 67);\n"
"}")
        self.reg_login_input.setText("")
        self.reg_login_input.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.reg_login_input.setObjectName("reg_login_input")
        self.label = QtWidgets.QLabel(self.register_container)
        self.label.setGeometry(QtCore.QRect(70, 0, 121, 20))
        self.label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.label.setObjectName("label")
        self.login_reg_stacked.addWidget(self.register_content)
        self.horizontalLayout.addWidget(self.frame)
        login_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(login_window)
        self.login_reg_stacked.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(login_window)

    def retranslateUi(self, login_window):
        _translate = QtCore.QCoreApplication.translate
        login_window.setWindowTitle(_translate("login_window", "MainWindow"))
        self.name_label.setText(_translate("login_window", "<html><head/><body><p><span style=\" font-weight:700;\">Scrabble</span></p><p><br/></p></body></html>"))
        self.emoji_label.setText(_translate("login_window", "<html><head/><body><p><img src=\":/newPrefix/images/3x.png\"/></p></body></html>"))
        self.register_button.setText(_translate("login_window", "nowy gracz?"))
        self.password_input.setPlaceholderText(_translate("login_window", "password"))
        self.login_button.setText(_translate("login_window", "zaloguj"))
        self.login_input.setPlaceholderText(_translate("login_window", "login"))
        self.label_2.setText(_translate("login_window", "<html><head/><body><p><span style=\" font-weight:700; font-style:italic;\">Zaloguj się</span></p></body></html>"))
        self.init_register_button.setText(_translate("login_window", "zarejetruj"))
        self.reg_password_input.setPlaceholderText(_translate("login_window", "password"))
        self.init_login_button.setText(_translate("login_window", "logowanie"))
        self.reg_login_input.setPlaceholderText(_translate("login_window", "login"))
        self.label.setText(_translate("login_window", "<html><head/><body><p><span style=\" font-weight:700; font-style:italic;\">Utwórz konto</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_window = QtWidgets.QMainWindow()
    ui = Ui_login_window()
    ui.setupUi(login_window)
    login_window.show()
    sys.exit(app.exec())
