# Form implementation generated from reading ui file '/Users/mzieba/Documents/szkola/code/Scrabble_with_GUI/templates/menu_window.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_menu_window(object):
    def setupUi(self, menu_window):
        menu_window.setObjectName("menu_window")
        menu_window.resize(526, 608)
        self.centralwidget = QtWidgets.QWidget(menu_window)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu_frame = QtWidgets.QFrame(self.centralwidget)
        self.menu_frame.setStyleSheet("QFrame {\n"
"    border-radius: 7px;\n"
"    color: rgb(62, 231, 41);\n"
"    background-color: rgb(40, 109, 50);\n"
"}\n"
"")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.name_label = QtWidgets.QLabel(self.menu_frame)
        self.name_label.setGeometry(QtCore.QRect(-190, 20, 661, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.exit_button = QtWidgets.QPushButton(self.menu_frame)
        self.exit_button.setGeometry(QtCore.QRect(489, 5, 14, 14))
        self.exit_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 40, 54);\n"
"    border-radius: 7px;\n"
"    border: none\n"
"}")
        self.exit_button.setText("")
        self.exit_button.setCheckable(False)
        self.exit_button.setDefault(False)
        self.exit_button.setFlat(False)
        self.exit_button.setObjectName("exit_button")
        self.emoji_label = QtWidgets.QLabel(self.menu_frame)
        self.emoji_label.setGeometry(QtCore.QRect(40, 440, 151, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.emoji_label.setFont(font)
        self.emoji_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.emoji_label.setObjectName("emoji_label")
        self.game_mode_frame = QtWidgets.QFrame(self.menu_frame)
        self.game_mode_frame.setGeometry(QtCore.QRect(40, 110, 231, 311))
        self.game_mode_frame.setStyleSheet("QFrame {\n"
"background-color: rgb(22, 60, 27);\n"
"}\n"
"")
        self.game_mode_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.game_mode_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.game_mode_frame.setObjectName("game_mode_frame")
        self.game_mode_label = QtWidgets.QLabel(self.game_mode_frame)
        self.game_mode_label.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.game_mode_label.setFont(font)
        self.game_mode_label.setStyleSheet("QLabel {\n"
"    color: rgb(226, 224, 158);\n"
"\n"
"}")
        self.game_mode_label.setObjectName("game_mode_label")
        self.hotseat_mode_label = QtWidgets.QLabel(self.game_mode_frame)
        self.hotseat_mode_label.setGeometry(QtCore.QRect(30, 240, 58, 16))
        self.hotseat_mode_label.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.hotseat_mode_label.setObjectName("hotseat_mode_label")
        self.ai_mode_label = QtWidgets.QLabel(self.game_mode_frame)
        self.ai_mode_label.setGeometry(QtCore.QRect(120, 240, 91, 20))
        self.ai_mode_label.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.ai_mode_label.setObjectName("ai_mode_label")
        self.game_mode_desc = QtWidgets.QTextBrowser(self.game_mode_frame)
        self.game_mode_desc.setGeometry(QtCore.QRect(40, 70, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        self.game_mode_desc.setFont(font)
        self.game_mode_desc.setStyleSheet("QWidget{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.game_mode_desc.setObjectName("game_mode_desc")
        self.hotseat_button = QtWidgets.QPushButton(self.game_mode_frame)
        self.hotseat_button.setGeometry(QtCore.QRect(20, 171, 101, 51))
        self.hotseat_button.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"    \n"
"}")
        self.hotseat_button.setText("")
        self.hotseat_button.setObjectName("hotseat_button")
        self.vs_si_button = QtWidgets.QPushButton(self.game_mode_frame)
        self.vs_si_button.setGeometry(QtCore.QRect(110, 170, 111, 51))
        self.vs_si_button.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    image: url(:/newPrefix/images/swords.png);\n"
"}")
        self.vs_si_button.setText("")
        self.vs_si_button.setObjectName("vs_si_button")
        self.ranking_frame = QtWidgets.QFrame(self.menu_frame)
        self.ranking_frame.setGeometry(QtCore.QRect(290, 110, 171, 221))
        self.ranking_frame.setStyleSheet("QFrame {\n"
"background-color: rgb(22, 60, 27);\n"
"}\n"
"")
        self.ranking_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ranking_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ranking_frame.setObjectName("ranking_frame")
        self.ranking_label = QtWidgets.QLabel(self.ranking_frame)
        self.ranking_label.setGeometry(QtCore.QRect(10, 15, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.ranking_label.setFont(font)
        self.ranking_label.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(226, 224, 158);\n"
"}")
        self.ranking_label.setObjectName("ranking_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.ranking_frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 50, 154, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.rank_vert_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.rank_vert_layout.setContentsMargins(0, 0, 0, 0)
        self.rank_vert_layout.setObjectName("rank_vert_layout")
        self.player1_h_lay = QtWidgets.QHBoxLayout()
        self.player1_h_lay.setObjectName("player1_h_lay")
        self.p1_name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        self.p1_name_label.setFont(font)
        self.p1_name_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.p1_name_label.setObjectName("p1_name_label")
        self.player1_h_lay.addWidget(self.p1_name_label)
        self.p1_score_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        self.p1_score_label.setFont(font)
        self.p1_score_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.p1_score_label.setObjectName("p1_score_label")
        self.player1_h_lay.addWidget(self.p1_score_label)
        self.rank_vert_layout.addLayout(self.player1_h_lay)
        self.player4_h_lay = QtWidgets.QHBoxLayout()
        self.player4_h_lay.setObjectName("player4_h_lay")
        self.p2_name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        self.p2_name_label.setFont(font)
        self.p2_name_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.p2_name_label.setObjectName("p2_name_label")
        self.player4_h_lay.addWidget(self.p2_name_label)
        self.p2_score_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        self.p2_score_label.setFont(font)
        self.p2_score_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.p2_score_label.setObjectName("p2_score_label")
        self.player4_h_lay.addWidget(self.p2_score_label)
        self.rank_vert_layout.addLayout(self.player4_h_lay)
        self.player5_h_lay = QtWidgets.QHBoxLayout()
        self.player5_h_lay.setObjectName("player5_h_lay")
        self.p3_name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        self.p3_name_label.setFont(font)
        self.p3_name_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.p3_name_label.setObjectName("p3_name_label")
        self.player5_h_lay.addWidget(self.p3_name_label)
        self.p3_score_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        self.p3_score_label.setFont(font)
        self.p3_score_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.p3_score_label.setObjectName("p3_score_label")
        self.player5_h_lay.addWidget(self.p3_score_label)
        self.rank_vert_layout.addLayout(self.player5_h_lay)
        self.player3_h_lay = QtWidgets.QHBoxLayout()
        self.player3_h_lay.setObjectName("player3_h_lay")
        self.p4_name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        self.p4_name_label.setFont(font)
        self.p4_name_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.p4_name_label.setObjectName("p4_name_label")
        self.player3_h_lay.addWidget(self.p4_name_label)
        self.p4_score_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        self.p4_score_label.setFont(font)
        self.p4_score_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.p4_score_label.setObjectName("p4_score_label")
        self.player3_h_lay.addWidget(self.p4_score_label)
        self.rank_vert_layout.addLayout(self.player3_h_lay)
        self.player2_h_lay = QtWidgets.QHBoxLayout()
        self.player2_h_lay.setObjectName("player2_h_lay")
        self.p5_name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        self.p5_name_label.setFont(font)
        self.p5_name_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.p5_name_label.setObjectName("p5_name_label")
        self.player2_h_lay.addWidget(self.p5_name_label)
        self.p5_score_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        self.p5_score_label.setFont(font)
        self.p5_score_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.p5_score_label.setObjectName("p5_score_label")
        self.player2_h_lay.addWidget(self.p5_score_label)
        self.rank_vert_layout.addLayout(self.player2_h_lay)
        self.misc_frame = QtWidgets.QFrame(self.menu_frame)
        self.misc_frame.setGeometry(QtCore.QRect(290, 350, 171, 201))
        self.misc_frame.setStyleSheet("QFrame {\n"
"background-color: rgb(22, 60, 27);\n"
"}\n"
"")
        self.misc_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.misc_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.misc_frame.setObjectName("misc_frame")
        self.misc_label = QtWidgets.QLabel(self.misc_frame)
        self.misc_label.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.misc_label.setFont(font)
        self.misc_label.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(226, 224, 158);\n"
"}")
        self.misc_label.setObjectName("misc_label")
        self.logout_button = QtWidgets.QPushButton(self.misc_frame)
        self.logout_button.setGeometry(QtCore.QRect(90, 150, 71, 32))
        self.logout_button.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"image: url(:/newPrefix/images/returnleft.png);\n"
"}\n"
"")
        self.logout_button.setText("")
        self.logout_button.setObjectName("logout_button")
        self.help_button = QtWidgets.QPushButton(self.misc_frame)
        self.help_button.setGeometry(QtCore.QRect(90, 70, 71, 32))
        self.help_button.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"image: url(:/newPrefix/images/lookingglass.png);\n"
"}\n"
"")
        self.help_button.setText("")
        self.help_button.setObjectName("help_button")
        self.account_button = QtWidgets.QPushButton(self.misc_frame)
        self.account_button.setGeometry(QtCore.QRect(90, 110, 71, 32))
        self.account_button.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"    image: url(:/newPrefix/images/edit.png);\n"
"}")
        self.account_button.setText("")
        self.account_button.setObjectName("account_button")
        self.help_label = QtWidgets.QLabel(self.misc_frame)
        self.help_label.setGeometry(QtCore.QRect(30, 75, 58, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.help_label.setFont(font)
        self.help_label.setStyleSheet("QLabel{\n"
"    color: rgb(226, 225, 158);\n"
"}")
        self.help_label.setObjectName("help_label")
        self.acc_manage_label = QtWidgets.QLabel(self.misc_frame)
        self.acc_manage_label.setGeometry(QtCore.QRect(30, 115, 58, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.acc_manage_label.setFont(font)
        self.acc_manage_label.setStyleSheet("QLabel{\n"
"    color: rgb(226, 225, 158);\n"
"}")
        self.acc_manage_label.setObjectName("acc_manage_label")
        self.logout_label = QtWidgets.QLabel(self.misc_frame)
        self.logout_label.setGeometry(QtCore.QRect(30, 155, 58, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.logout_label.setFont(font)
        self.logout_label.setStyleSheet("QLabel{\n"
"    color: rgb(226, 225, 158);\n"
"}")
        self.logout_label.setObjectName("logout_label")
        self.horizontalLayout.addWidget(self.menu_frame)
        menu_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(menu_window)
        QtCore.QMetaObject.connectSlotsByName(menu_window)

    def retranslateUi(self, menu_window):
        _translate = QtCore.QCoreApplication.translate
        menu_window.setWindowTitle(_translate("menu_window", "MainWindow"))
        self.name_label.setText(_translate("menu_window", "<html><head/><body><p><span style=\" font-weight:700;\">Scrabble</span></p><p><br/></p></body></html>"))
        self.emoji_label.setText(_translate("menu_window", "<html><head/><body><p><img src=\":/newPrefix/images/3x.png\"/></p></body></html>"))
        self.game_mode_label.setText(_translate("menu_window", "<html><head/><body><p><span style=\" font-size:18pt;\">Tryb gry</span></p></body></html>"))
        self.hotseat_mode_label.setText(_translate("menu_window", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:700; font-style:italic;\">hot seat</span></p></body></html>"))
        self.ai_mode_label.setText(_translate("menu_window", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700; font-style:italic;\">kontra SI</span></p></body></html>"))
        self.game_mode_desc.setHtml(_translate("menu_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:14pt; font-weight:700; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13pt;\">wybierz jeden z trybów gry i zmierz się ze znajomymi lub automatem!</span></p></body></html>"))
        self.ranking_label.setText(_translate("menu_window", "<html><head/><body><p><span style=\" font-size:18pt;\">Top 5</span></p></body></html>"))
        self.p1_name_label.setText(_translate("menu_window", "pholder"))
        self.p1_score_label.setText(_translate("menu_window", "pholder"))
        self.p2_name_label.setText(_translate("menu_window", "pholder"))
        self.p2_score_label.setText(_translate("menu_window", "pholder"))
        self.p3_name_label.setText(_translate("menu_window", "pholder"))
        self.p3_score_label.setText(_translate("menu_window", "pholder"))
        self.p4_name_label.setText(_translate("menu_window", "pholder"))
        self.p4_score_label.setText(_translate("menu_window", "pholder"))
        self.p5_name_label.setText(_translate("menu_window", "pholder"))
        self.p5_score_label.setText(_translate("menu_window", "pholder"))
        self.misc_label.setText(_translate("menu_window", "<html><head/><body><p><span style=\" font-size:18pt;\">Opcje</span></p></body></html>"))
        self.help_label.setText(_translate("menu_window", "pomoc"))
        self.acc_manage_label.setText(_translate("menu_window", "konto"))
        self.logout_label.setText(_translate("menu_window", "wyloguj"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menu_window = QtWidgets.QMainWindow()
    ui = Ui_menu_window()
    ui.setupUi(menu_window)
    menu_window.show()
    sys.exit(app.exec())
