# Form implementation generated from reading ui file '/Users/mzieba/Documents/szkola/code/Scrabble_with_GUI/templates/sisi_mode_window.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_sisi_mode_window(object):
    def setupUi(self, sisi_mode_window):
        sisi_mode_window.setObjectName("sisi_mode_window")
        sisi_mode_window.resize(600, 650)
        self.centralwidget = QtWidgets.QWidget(sisi_mode_window)
        self.centralwidget.setObjectName("centralwidget")
        self.menu_frame = QtWidgets.QFrame(self.centralwidget)
        self.menu_frame.setGeometry(QtCore.QRect(140, 60, 311, 501))
        self.menu_frame.setStyleSheet("QFrame {\n"
"    border-radius: 7px;\n"
"    color: rgb(62, 231, 41);\n"
"    background-color: rgb(40, 109, 50);\n"
"}\n"
"")
        self.menu_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.name_label = QtWidgets.QLabel(self.menu_frame)
        self.name_label.setGeometry(QtCore.QRect(-40, 20, 361, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.name_label.setObjectName("name_label")
        self.exit_button = QtWidgets.QPushButton(self.menu_frame)
        self.exit_button.setGeometry(QtCore.QRect(290, 7, 14, 14))
        self.exit_button.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 40, 54);\n"
"    border-radius: 7px;\n"
"    border: none\n"
"}")
        self.exit_button.setText("")
        self.exit_button.setCheckable(False)
        self.exit_button.setDefault(False)
        self.exit_button.setFlat(False)
        self.exit_button.setObjectName("exit_button")
        self.game_mode_stacked = QtWidgets.QStackedWidget(self.menu_frame)
        self.game_mode_stacked.setGeometry(QtCore.QRect(40, 110, 231, 341))
        self.game_mode_stacked.setStyleSheet("QWidget {\n"
"background-color: rgb(22, 60, 27);\n"
"border-radius:10px;\n"
"}\n"
"")
        self.game_mode_stacked.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.game_mode_stacked.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.game_mode_stacked.setObjectName("game_mode_stacked")
        self.player_si_level_select_page = QtWidgets.QWidget()
        self.player_si_level_select_page.setStyleSheet("QFrame {\n"
"background-color: rgb(22, 60, 27);\n"
"}\n"
"")
        self.player_si_level_select_page.setObjectName("player_si_level_select_page")
        self.hard_si_button = QtWidgets.QPushButton(self.player_si_level_select_page)
        self.hard_si_button.setGeometry(QtCore.QRect(140, 169, 50, 121))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hard_si_button.setFont(font)
        self.hard_si_button.setStyleSheet("QPushButton{\n"
"    border-radius: 20;\n"
"    background-color: rgb(255, 50, 58);\n"
"}")
        self.hard_si_button.setText("")
        self.hard_si_button.setObjectName("hard_si_button")
        self.game_mode_label_2 = QtWidgets.QLabel(self.player_si_level_select_page)
        self.game_mode_label_2.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.game_mode_label_2.setFont(font)
        self.game_mode_label_2.setStyleSheet("QLabel {\n"
"    color: rgb(226, 224, 158);\n"
"\n"
"}")
        self.game_mode_label_2.setObjectName("game_mode_label_2")
        self.si_mode_label_2 = QtWidgets.QLabel(self.player_si_level_select_page)
        self.si_mode_label_2.setGeometry(QtCore.QRect(90, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.si_mode_label_2.setFont(font)
        self.si_mode_label_2.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(62, 232, 41);\n"
"}")
        self.si_mode_label_2.setObjectName("si_mode_label_2")
        self.easy_si_button = QtWidgets.QPushButton(self.player_si_level_select_page)
        self.easy_si_button.setGeometry(QtCore.QRect(40, 220, 50, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.easy_si_button.setFont(font)
        self.easy_si_button.setStyleSheet("QPushButton{\n"
"    border-radius: 20;\n"
"background-color: rgb(141, 255, 133);\n"
"}")
        self.easy_si_button.setText("")
        self.easy_si_button.setObjectName("easy_si_button")
        self.si_icon_label_2 = QtWidgets.QLabel(self.player_si_level_select_page)
        self.si_icon_label_2.setGeometry(QtCore.QRect(40, 65, 41, 41))
        self.si_icon_label_2.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.si_icon_label_2.setText("")
        self.si_icon_label_2.setObjectName("si_icon_label_2")
        self.game_mode_desc_2 = QtWidgets.QTextBrowser(self.player_si_level_select_page)
        self.game_mode_desc_2.setGeometry(QtCore.QRect(20, 120, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        self.game_mode_desc_2.setFont(font)
        self.game_mode_desc_2.setStyleSheet("QWidget{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.game_mode_desc_2.setObjectName("game_mode_desc_2")
        self.game_mode_stacked.addWidget(self.player_si_level_select_page)
        self.sisi_level_select_page = QtWidgets.QWidget()
        self.sisi_level_select_page.setObjectName("sisi_level_select_page")
        self.si_mode_label_3 = QtWidgets.QLabel(self.sisi_level_select_page)
        self.si_mode_label_3.setGeometry(QtCore.QRect(90, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.si_mode_label_3.setFont(font)
        self.si_mode_label_3.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(62, 232, 41);\n"
"}")
        self.si_mode_label_3.setObjectName("si_mode_label_3")
        self.game_mode_label_3 = QtWidgets.QLabel(self.sisi_level_select_page)
        self.game_mode_label_3.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.game_mode_label_3.setFont(font)
        self.game_mode_label_3.setStyleSheet("QLabel {\n"
"    color: rgb(226, 224, 158);\n"
"\n"
"}")
        self.game_mode_label_3.setObjectName("game_mode_label_3")
        self.game_mode_desc_3 = QtWidgets.QTextBrowser(self.sisi_level_select_page)
        self.game_mode_desc_3.setGeometry(QtCore.QRect(20, 110, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        self.game_mode_desc_3.setFont(font)
        self.game_mode_desc_3.setStyleSheet("QWidget{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.game_mode_desc_3.setObjectName("game_mode_desc_3")
        self.si_icon_label_3 = QtWidgets.QLabel(self.sisi_level_select_page)
        self.si_icon_label_3.setGeometry(QtCore.QRect(40, 65, 41, 41))
        self.si_icon_label_3.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.si_icon_label_3.setText("")
        self.si_icon_label_3.setObjectName("si_icon_label_3")
        self.si_icon_label_4 = QtWidgets.QLabel(self.sisi_level_select_page)
        self.si_icon_label_4.setGeometry(QtCore.QRect(40, 190, 41, 41))
        self.si_icon_label_4.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.si_icon_label_4.setText("")
        self.si_icon_label_4.setObjectName("si_icon_label_4")
        self.si_icon_label_5 = QtWidgets.QLabel(self.sisi_level_select_page)
        self.si_icon_label_5.setGeometry(QtCore.QRect(150, 190, 41, 41))
        self.si_icon_label_5.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.si_icon_label_5.setText("")
        self.si_icon_label_5.setObjectName("si_icon_label_5")
        self.si1_easy_checkbox = QtWidgets.QCheckBox(self.sisi_level_select_page)
        self.si1_easy_checkbox.setGeometry(QtCore.QRect(40, 250, 85, 20))
        self.si1_easy_checkbox.setObjectName("si1_easy_checkbox")
        self.si1_hard_checkbox = QtWidgets.QCheckBox(self.sisi_level_select_page)
        self.si1_hard_checkbox.setGeometry(QtCore.QRect(40, 280, 85, 20))
        self.si1_hard_checkbox.setObjectName("si1_hard_checkbox")
        self.si2_hard_checkbox = QtWidgets.QCheckBox(self.sisi_level_select_page)
        self.si2_hard_checkbox.setGeometry(QtCore.QRect(150, 280, 85, 20))
        self.si2_hard_checkbox.setObjectName("si2_hard_checkbox")
        self.si2_easy_checkbox = QtWidgets.QCheckBox(self.sisi_level_select_page)
        self.si2_easy_checkbox.setGeometry(QtCore.QRect(150, 250, 85, 20))
        self.si2_easy_checkbox.setObjectName("si2_easy_checkbox")
        self.sisi_game_button = QtWidgets.QPushButton(self.sisi_level_select_page)
        self.sisi_game_button.setGeometry(QtCore.QRect(100, 300, 41, 32))
        self.sisi_game_button.setText("")
        self.sisi_game_button.setObjectName("sisi_game_button")
        self.sisi_error_label = QtWidgets.QLabel(self.sisi_level_select_page)
        self.sisi_error_label.setGeometry(QtCore.QRect(40, 160, 151, 20))
        self.sisi_error_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.sisi_error_label.setObjectName("sisi_error_label")
        self.game_mode_stacked.addWidget(self.sisi_level_select_page)
        self.game_mode_select_page = QtWidgets.QWidget()
        self.game_mode_select_page.setObjectName("game_mode_select_page")
        self.game_mode_label = QtWidgets.QLabel(self.game_mode_select_page)
        self.game_mode_label.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        self.game_mode_label.setFont(font)
        self.game_mode_label.setStyleSheet("QLabel {\n"
"    color: rgb(226, 224, 158);\n"
"\n"
"}")
        self.game_mode_label.setObjectName("game_mode_label")
        self.si_mode_label = QtWidgets.QLabel(self.game_mode_select_page)
        self.si_mode_label.setGeometry(QtCore.QRect(90, 70, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.si_mode_label.setFont(font)
        self.si_mode_label.setStyleSheet("QLabel {\n"
"    \n"
"    color: rgb(62, 232, 41);\n"
"}")
        self.si_mode_label.setObjectName("si_mode_label")
        self.game_mode_desc = QtWidgets.QTextBrowser(self.game_mode_select_page)
        self.game_mode_desc.setGeometry(QtCore.QRect(30, 120, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        self.game_mode_desc.setFont(font)
        self.game_mode_desc.setStyleSheet("QWidget{\n"
"    \n"
"    color: rgb(204, 204, 143);\n"
"}")
        self.game_mode_desc.setObjectName("game_mode_desc")
        self.player_button = QtWidgets.QPushButton(self.game_mode_select_page)
        self.player_button.setGeometry(QtCore.QRect(40, 220, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.player_button.setFont(font)
        self.player_button.setStyleSheet("QPushButton{\n"
"    border-radius: 20;\n"
"    background-color: rgb(202, 78, 68);\n"
"}")
        self.player_button.setText("")
        self.player_button.setObjectName("player_button")
        self.simulate_button = QtWidgets.QPushButton(self.game_mode_select_page)
        self.simulate_button.setGeometry(QtCore.QRect(140, 220, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.simulate_button.setFont(font)
        self.simulate_button.setStyleSheet("QPushButton{\n"
"    border-radius: 20;\n"
"    background-color: rgb(202, 78, 68);\n"
"}")
        self.simulate_button.setText("")
        self.simulate_button.setObjectName("simulate_button")
        self.si_icon_label = QtWidgets.QLabel(self.game_mode_select_page)
        self.si_icon_label.setGeometry(QtCore.QRect(40, 65, 41, 41))
        self.si_icon_label.setStyleSheet("QLabel {\n"
"    \n"
"    image: url(:/newPrefix/images/gamer.png);\n"
"}")
        self.si_icon_label.setText("")
        self.si_icon_label.setObjectName("si_icon_label")
        self.label = QtWidgets.QLabel(self.game_mode_select_page)
        self.label.setGeometry(QtCore.QRect(38, 280, 58, 16))
        self.label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.label.setObjectName("label")
        self.sisi_label = QtWidgets.QLabel(self.game_mode_select_page)
        self.sisi_label.setGeometry(QtCore.QRect(136, 280, 58, 16))
        self.sisi_label.setAlignment(QtCore.Qt.Alignment.AlignCenter)
        self.sisi_label.setObjectName("sisi_label")
        self.game_mode_stacked.addWidget(self.game_mode_select_page)
        self.return_to_menu_button = QtWidgets.QPushButton(self.menu_frame)
        self.return_to_menu_button.setGeometry(QtCore.QRect(140, 460, 41, 32))
        self.return_to_menu_button.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"image: url(:/newPrefix/images/returnleft.png);\n"
"}\n"
"")
        self.return_to_menu_button.setText("")
        self.return_to_menu_button.setObjectName("return_to_menu_button")
        sisi_mode_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(sisi_mode_window)
        self.game_mode_stacked.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(sisi_mode_window)

    def retranslateUi(self, sisi_mode_window):
        _translate = QtCore.QCoreApplication.translate
        sisi_mode_window.setWindowTitle(_translate("sisi_mode_window", "MainWindow"))
        self.name_label.setText(_translate("sisi_mode_window", "<html><head/><body><p><span style=\" font-weight:700;\">Scrabble</span></p><p><br/></p></body></html>"))
        self.game_mode_label_2.setText(_translate("sisi_mode_window", "<html><head/><body><p><span style=\" font-size:18pt;\">Tryb gry</span></p></body></html>"))
        self.si_mode_label_2.setText(_translate("sisi_mode_window", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:700; font-style:italic;\">vs SI mode</span></p></body></html>"))
        self.game_mode_desc_2.setHtml(_translate("sisi_mode_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:14pt; font-weight:700; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13pt;\">wybierz poziom trudności SI i zagraj!</span></p></body></html>"))
        self.si_mode_label_3.setText(_translate("sisi_mode_window", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:700; font-style:italic;\">SI vs SI </span></p></body></html>"))
        self.game_mode_label_3.setText(_translate("sisi_mode_window", "<html><head/><body><p><span style=\" font-size:18pt;\">Tryb gry</span></p></body></html>"))
        self.game_mode_desc_3.setHtml(_translate("sisi_mode_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:14pt; font-weight:700; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13pt;\">wybierz poziom trudności współgrających SI</span></p></body></html>"))
        self.si1_easy_checkbox.setText(_translate("sisi_mode_window", "easy"))
        self.si1_hard_checkbox.setText(_translate("sisi_mode_window", "hard"))
        self.si2_hard_checkbox.setText(_translate("sisi_mode_window", "hard"))
        self.si2_easy_checkbox.setText(_translate("sisi_mode_window", "easy"))
        self.sisi_error_label.setText(_translate("sisi_mode_window", "TextLabel"))
        self.game_mode_label.setText(_translate("sisi_mode_window", "<html><head/><body><p><span style=\" font-size:18pt;\">Tryb gry</span></p></body></html>"))
        self.si_mode_label.setText(_translate("sisi_mode_window", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:700; font-style:italic;\">vs SI mode</span></p></body></html>"))
        self.game_mode_desc.setHtml(_translate("sisi_mode_window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:14pt; font-weight:700; font-style:italic;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:13pt;\">w tym trybie rozgrywki zmierzysz z automatem, lub zaobserwujesz grę SI vs SI</span></p></body></html>"))
        self.label.setText(_translate("sisi_mode_window", "zagraj!"))
        self.sisi_label.setText(_translate("sisi_mode_window", "SI vs SI"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    sisi_mode_window = QtWidgets.QMainWindow()
    ui = Ui_sisi_mode_window()
    ui.setupUi(sisi_mode_window)
    sisi_mode_window.show()
    sys.exit(app.exec())
